openapi: 3.0.1
info:
  title: foerdermittel-backend
  description: Backend component for the application foerdermittel
  version: 0.0.1-SNAPSHOT
servers:
- url: http://localhost:8086
  description: Generated server url
tags:
- name: Actuator
  description: Monitor and interact
  externalDocs:
    description: Spring Boot Actuator Web API Documentation
    url: https://docs.spring.io/spring-boot/docs/current/actuator-api/html/
paths:
  /bauprogramme/{id}:
    get:
      tags:
      - bauprogramm-controller
      operationId: getBauprogramm
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BauprogrammResponseDTO"
      security:
      - bearerAuth: []
    put:
      tags:
      - bauprogramm-controller
      operationId: updateBauprogramm
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BauprogrammUpdateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BauprogrammResponseDTO"
      security:
      - bearerAuth: []
    delete:
      tags:
      - bauprogramm-controller
      operationId: deleteBauprogramm
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
      security:
      - bearerAuth: []
  /bauprogramme:
    get:
      tags:
      - bauprogramm-controller
      operationId: getBauprogrammeByPageAndSize
      parameters:
      - name: pageNumber
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: pageSize
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedModelBauprogrammResponseDTO"
      security:
      - bearerAuth: []
    post:
      tags:
      - bauprogramm-controller
      operationId: saveBauprogramm
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BauprogrammCreateDTO"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BauprogrammResponseDTO"
      security:
      - bearerAuth: []
  /actuator:
    get:
      tags:
      - Actuator
      summary: Actuator root web endpoint
      operationId: links
      responses:
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
  /actuator/sbom:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'sbom'
      operationId: sboms
      responses:
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
  /actuator/sbom/{id}:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'sbom-id'
      operationId: sbom
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/octet-stream:
              schema:
                type: object
        "404":
          description: Not Found
  /actuator/metrics:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'prometheus'
      operationId: scrape
      parameters:
      - name: format
        in: query
        schema:
          type: string
          enum:
          - CONTENT_TYPE_004
          - CONTENT_TYPE_OPENMETRICS_100
          - CONTENT_TYPE_PROTOBUF
      - name: includedNames
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain;version=0.0.4;charset=utf-8:
              schema:
                type: object
            application/openmetrics-text;version=1.0.0;charset=utf-8:
              schema:
                type: object
            application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited:
              schema:
                type: object
  /actuator/info:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'info'
      operationId: info
      responses:
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
  /actuator/health:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'health'
      operationId: health
      responses:
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
components:
  schemas:
    BauprogrammUpdateDTO:
      required:
      - bezeichnung
      type: object
      properties:
        bezeichnung:
          maxLength: 200
          minLength: 0
          type: string
    BauprogrammResponseDTO:
      required:
      - bauprogramm
      - bezeichnung
      - id
      type: object
      properties:
        id:
          type: string
        bauprogramm:
          type: integer
          format: int32
        bezeichnung:
          type: string
    BauprogrammCreateDTO:
      required:
      - bauprogramm
      - bezeichnung
      type: object
      properties:
        bauprogramm:
          maximum: 99
          minimum: 1
          type: integer
          format: int32
        bezeichnung:
          maxLength: 200
          minLength: 0
          type: string
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
    PagedModelBauprogrammResponseDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/BauprogrammResponseDTO"
        page:
          $ref: "#/components/schemas/PageMetadata"
    Link:
      type: object
      properties:
        href:
          type: string
        templated:
          type: boolean
  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      scheme: bearer
      bearerFormat: JWT
