openapi: 3.0.1
info:
  title: foerdermittel-backend
  description: Backend component for the application foerdermittel
  version: 0.0.1-SNAPSHOT
servers:
- url: http://localhost:8086
  description: Generated server url
tags:
- name: Actuator
  description: Monitor and interact
  externalDocs:
    description: Spring Boot Actuator Web API Documentation
    url: https://docs.spring.io/spring-boot/docs/current/actuator-api/html/
paths:
  /siedlungsgebiet/{id}:
    get:
      tags:
      - siedlungsgebiet-controller
      operationId: getSiedlungsgebiet
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SiedlungsgebietResponseDTO"
      security:
      - bearerAuth: []
    put:
      tags:
      - siedlungsgebiet-controller
      operationId: updateSiedlungsgebiet
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SiedlungsgebietUpdateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SiedlungsgebietResponseDTO"
      security:
      - bearerAuth: []
    delete:
      tags:
      - siedlungsgebiet-controller
      operationId: deleteSiedlungsgebiet
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
      security:
      - bearerAuth: []
  /siedlungsgebiet:
    get:
      tags:
      - siedlungsgebiet-controller
      operationId: getSiedlungsgebieteByPageAndSize
      parameters:
      - name: pageNumber
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: pageSize
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedModelSiedlungsgebietResponseDTO"
      security:
      - bearerAuth: []
    post:
      tags:
      - siedlungsgebiet-controller
      operationId: saveSiedlungsgebiet
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SiedlungsgebietCreateDTO"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SiedlungsgebietResponseDTO"
      security:
      - bearerAuth: []
  /actuator:
    get:
      tags:
      - Actuator
      summary: Actuator root web endpoint
      operationId: links
      responses:
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: "#/components/schemas/Link"
  /actuator/sbom:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'sbom'
      operationId: sboms
      responses:
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
  /actuator/sbom/{id}:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'sbom-id'
      operationId: sbom
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/octet-stream:
              schema:
                type: object
        "404":
          description: Not Found
  /actuator/metrics:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'prometheus'
      operationId: scrape
      parameters:
      - name: format
        in: query
        schema:
          type: string
          enum:
          - CONTENT_TYPE_004
          - CONTENT_TYPE_OPENMETRICS_100
          - CONTENT_TYPE_PROTOBUF
      - name: includedNames
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain;version=0.0.4;charset=utf-8:
              schema:
                type: object
            application/openmetrics-text;version=1.0.0;charset=utf-8:
              schema:
                type: object
            application/vnd.google.protobuf;proto=io.prometheus.client.MetricFamily;encoding=delimited:
              schema:
                type: object
  /actuator/info:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'info'
      operationId: info
      responses:
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
  /actuator/health:
    get:
      tags:
      - Actuator
      summary: Actuator web endpoint 'health'
      operationId: health
      responses:
        "200":
          description: OK
          content:
            application/vnd.spring-boot.actuator.v3+json:
              schema:
                type: object
            application/vnd.spring-boot.actuator.v2+json:
              schema:
                type: object
            application/json:
              schema:
                type: object
components:
  schemas:
    SiedlungsgebietUpdateDTO:
      required:
      - bezeichnung
      type: object
      properties:
        bezeichnung:
          maxLength: 200
          minLength: 0
          type: string
    SiedlungsgebietResponseDTO:
      type: object
      properties:
        id:
          type: string
        siedlungsgebiet:
          type: integer
          format: int32
        bezeichnung:
          type: string
    SiedlungsgebietCreateDTO:
      required:
      - bezeichnung
      - siedlungsgebiet
      type: object
      properties:
        siedlungsgebiet:
          maximum: 99
          minimum: 1
          type: integer
          format: int32
        bezeichnung:
          maxLength: 200
          minLength: 0
          type: string
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
    PagedModelSiedlungsgebietResponseDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/SiedlungsgebietResponseDTO"
        page:
          $ref: "#/components/schemas/PageMetadata"
    Link:
      type: object
      properties:
        href:
          type: string
        templated:
          type: boolean
  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      scheme: bearer
      bearerFormat: JWT
