--------------------------------------------------------
--  DDL for Table FP_STICHWORTBEREICHE
--------------------------------------------------------

CREATE TABLE fp_stichwortbereiche
(
    bereich     VARCHAR(30) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN fp_stichwortbereiche.bereich IS 'Definierter Bereich für die Stichwortvergabe';
COMMENT ON COLUMN fp_stichwortbereiche.bezeichnung IS 'Bezeichnung dieses Stichwortbereichs';
COMMENT ON TABLE fp_stichwortbereiche IS 'Verzeichnis aller Stichwortbereiche (Nutzung in Ablageindexe)';
--------------------------------------------------------
--  DDL for Table FP_ABLAGEINDEXE
--------------------------------------------------------

CREATE TABLE fp_ablageindexe
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stb_bereich VARCHAR(30) NOT NULL REFERENCES fp_stichwortbereiche (bereich),
    nr          NUMERIC(4, 0),
    wort        VARCHAR(80),
    stichworte  VARCHAR(400)
);

COMMENT ON COLUMN fp_ablageindexe.id IS 'Primary Key (Sequence)';
COMMENT ON COLUMN fp_ablageindexe.stb_bereich IS 'Bereich und Bezeichnung des Ablagedeckblattes';
COMMENT ON COLUMN fp_ablageindexe.nr IS 'Lfd. Nummer innerhalb des Deckblattes';
COMMENT ON COLUMN fp_ablageindexe.wort IS 'Thema des Schriftgutes';
COMMENT ON COLUMN fp_ablageindexe.stichworte IS 'Stichwort (Index) nach dem gesucht werden kann';
COMMENT ON TABLE fp_ablageindexe IS 'Suchindex zum Auffinden von Ablagen (dbase:hinh)';
--------------------------------------------------------
--  DDL for Table FP_REFERATE
--------------------------------------------------------

CREATE TABLE fp_referate
(
    refnr       NUMERIC(2, 0) PRIMARY KEY,
    bezeichnung VARCHAR(200)
);

COMMENT ON COLUMN fp_referate.refnr IS 'Nummer des Referats';
COMMENT ON COLUMN fp_referate.bezeichnung IS 'Beschreibung des Referats';
COMMENT ON TABLE fp_referate IS 'Aufstellung aller Referate  (dbase:referate)';
--------------------------------------------------------
--  DDL for Table FP_FOERDERBEREICHE
--------------------------------------------------------

CREATE TABLE fp_foerderbereiche
(
    fb          NUMERIC(2, 0) PRIMARY KEY,
    bezeichnung VARCHAR(200)          NOT NULL,
    funktion1   BOOLEAN DEFAULT FALSE NOT NULL,
    funktion2   BOOLEAN DEFAULT FALSE NOT NULL,
    funktion3   BOOLEAN DEFAULT FALSE NOT NULL,
    funktion4   BOOLEAN DEFAULT FALSE NOT NULL
);

COMMENT ON COLUMN fp_foerderbereiche.fb IS 'Abkürzung des Förderbereichs';
COMMENT ON COLUMN fp_foerderbereiche.bezeichnung IS 'Bezeichnung des Förderbereichs';
COMMENT ON COLUMN fp_foerderbereiche.funktion1 IS 'Soll der Förderbereich in der FAG-Statistik verwendet werden';
COMMENT ON COLUMN fp_foerderbereiche.funktion2 IS 'Soll der Förderbereich in der Jahresstatistik verwendet werden';
COMMENT ON COLUMN fp_foerderbereiche.funktion3 IS 'Ist der Förderbereich vom Typ Kindergarten. Wird verwendet in Jahresstatistik.';
COMMENT ON COLUMN fp_foerderbereiche.funktion4 IS 'Der Förderbereich kann als nicht relevant gekennzeichnet werden. Damit Aussteuerung in manchen Berichten';
COMMENT ON TABLE fp_foerderbereiche IS 'Austellung aller Förderbereiche (dbase:fb)';
--------------------------------------------------------
--  DDL for Table FP_KURZBEZEICHNUNGEN
--------------------------------------------------------

CREATE TABLE fp_kurzbezeichnungen
(
    kurzbez     VARCHAR(8) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN fp_kurzbezeichnungen.kurzbez IS 'Kurzbezeichnung für eine Projekt';
COMMENT ON COLUMN fp_kurzbezeichnungen.bezeichnung IS 'Beschreibung zu einer Kurzbezeichnung';
COMMENT ON TABLE fp_kurzbezeichnungen IS 'Alle Kurzbezeichnungen zur Klassiifzierung von Projekten  (dbase:kurzbez)';
--------------------------------------------------------
--  DDL for Table FP_HAUPTABSCHNITTE
--------------------------------------------------------

CREATE TABLE fp_hauptabschnitte
(
    ha          VARCHAR(2) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN fp_hauptabschnitte.ha IS 'Hauptabschnitt';
COMMENT ON COLUMN fp_hauptabschnitte.bezeichnung IS 'Bezeichnung des Hauptabschnitts';
COMMENT ON TABLE fp_hauptabschnitte IS 'Hauptabschnitte zur Klassifizierung der Unterabschnitte (dbase: keine Datei vorhanden)';
--------------------------------------------------------
--  DDL for Table FP_UNTERABSCHNITTE
--------------------------------------------------------

CREATE TABLE fp_unterabschnitte
(
    ua          VARCHAR(2) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL,
    has_ha      VARCHAR(2)   NOT NULL REFERENCES fp_hauptabschnitte (ha)
);

COMMENT ON COLUMN fp_unterabschnitte.ua IS 'Nummer des Unterabschnitts';
COMMENT ON COLUMN fp_unterabschnitte.bezeichnung IS 'Bezeichnung des Unterabschnitts';
COMMENT ON COLUMN fp_unterabschnitte.has_ha IS 'Nummer des Hauptabschnitt des UAs (FK)';
COMMENT ON TABLE fp_unterabschnitte IS 'Unterabschnitte als Teil1 der Projektnummer (dbase: keine Datei vorhanden)';
--------------------------------------------------------
--  DDL for Table FP_BAULEITUNGEN
--------------------------------------------------------

CREATE TABLE fp_bauleitungen
(
    bauleitung  VARCHAR(1) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN fp_bauleitungen.bauleitung IS 'Abkürzung der Bauleitung wie H,1,S';
COMMENT ON COLUMN fp_bauleitungen.bezeichnung IS 'Beschreibung der Bauleitung';
COMMENT ON TABLE fp_bauleitungen IS 'Aufstellung aller Bauleitungen als Stammdaten';
--------------------------------------------------------
--  DDL for Table FP_STADTBEZIRKE
--------------------------------------------------------

CREATE TABLE fp_stadtbezirke
(
    stadtbezirk NUMERIC(2, 0) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN fp_stadtbezirke.stadtbezirk IS 'Nummer des Stadtbezirks';
COMMENT ON COLUMN fp_stadtbezirke.bezeichnung IS 'Beschreibung des Bezirks';
COMMENT ON TABLE fp_stadtbezirke IS 'Aufstellung aller Stadtbezirke';
--------------------------------------------------------
--  DDL for Table FP_KRANKENHAEUSER
--------------------------------------------------------

CREATE TABLE fp_krankenhaeuser
(
    krhname     VARCHAR(1) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN fp_krankenhaeuser.krhname IS 'Abkürzung des Krankenhauses wie B, R';
COMMENT ON COLUMN fp_krankenhaeuser.bezeichnung IS 'Beschreibung des Krankenhauses';
COMMENT ON TABLE fp_krankenhaeuser IS 'Aufstellung aller Krankenhäuser als Stammdaten';
--------------------------------------------------------
--  DDL for Table FP_BAUPROGRAMME
--------------------------------------------------------

CREATE TABLE fp_bauprogramme
(
    bauprogramm NUMERIC(2, 0) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN fp_bauprogramme.bauprogramm IS 'Nummer des Bauprogramms';
COMMENT ON COLUMN fp_bauprogramme.bezeichnung IS 'Beschreibung des Bauprogramms';
COMMENT ON TABLE fp_bauprogramme IS 'Aufstellung aller Bauprogramme';
--------------------------------------------------------
--  DDL for Table FP_SIEDLUNGSGEBIETE
--------------------------------------------------------

CREATE TABLE fp_siedlungsgebiete
(
    siedlungsgebiet NUMERIC(2, 0) PRIMARY KEY,
    bezeichnung     VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN fp_siedlungsgebiete.siedlungsgebiet IS 'Nummer des Siedlungsgebiets';
COMMENT ON COLUMN fp_siedlungsgebiete.bezeichnung IS 'Beschreibung des Siedlungsgebiets';
COMMENT ON TABLE fp_siedlungsgebiete IS 'Aufstellung aller Siedlungsgebiete';
--------------------------------------------------------
--  DDL for Table FP_PROJEKTE
--------------------------------------------------------
CREATE TABLE fp_projekte
(
    projnr              VARCHAR(7) PRIMARY KEY,
    fob_fb              NUMERIC(2, 0)                    NOT NULL REFERENCES fp_foerderbereiche (fb),
    kur_kurzbez         VARCHAR(8)                       NOT NULL REFERENCES fp_kurzbezeichnungen (kurzbez),
    uas_ua              VARCHAR(2)                       NOT NULL REFERENCES fp_unterabschnitte (ua),
    jahr VARCHAR(2) NOT NULL,
    lfdnr1              VARCHAR(1)                       NOT NULL,
    lfdnr2              VARCHAR(2)                       NOT NULL,
    pname               VARCHAR(100),
    pstrasse            VARCHAR(100),
    kauf                BOOLEAN     DEFAULT FALSE        NOT NULL,
    projart             VARCHAR(50),
    refinanzierbar      BOOLEAN     DEFAULT TRUE         NOT NULL,
    ble_bauleitung      VARCHAR(1) REFERENCES fp_bauleitungen (bauleitung),
    bauleitungkontakt   VARCHAR(30),
    bez_stadtbezirk     NUMERIC(2, 0) REFERENCES fp_stadtbezirke (stadtbezirk),
    krn_krhname         VARCHAR(1) REFERENCES fp_krankenhaeuser (krhname),
    krhzweck            VARCHAR(1),
    krisofp             VARCHAR(1),
    kripplatz           NUMERIC(10, 0),
    kigaplatz           NUMERIC(10, 0),
    hortplatz           NUMERIC(10, 0),
    vndat               DATE,
    vnkosten            NUMERIC(12, 2),
    vnzwfkosten         NUMERIC(12, 2),
    vnpruefdat          DATE,
    vnrueck_z           NUMERIC(12, 2),
    vnnachfoerderung    NUMERIC(12, 2),
    vnpruefzwf          NUMERIC(12, 2),
    vnschlusszwf        NUMERIC(12, 2),
    vnschlussbew        DATE,
    sap                 BOOLEAN     DEFAULT FALSE        NOT NULL,
    sapstatauf          BOOLEAN     DEFAULT FALSE        NOT NULL,
    sapmatnr            NUMERIC(8, 0),
    sapwertnr           NUMERIC(8, 0),
    sapjahrwert         DATE,
    sapanlagennr        NUMERIC(8, 0),
    zinsen              NUMERIC(10, 0),
    zinsdatum           DATE,
    fipo                VARCHAR(15),
    buchungskreis       VARCHAR(4),
    sachkonto           VARCHAR(6),
    fipo_k              VARCHAR(15),
    buchungskreis_k     VARCHAR(4),
    sachkonto_k         VARCHAR(6),
    psbaubuch           VARCHAR(2),
    psbauref            VARCHAR(2),
    psbaunr             VARCHAR(6),
    notizen             TEXT,
    altdaten            BOOLEAN     DEFAULT FALSE        NOT NULL,
    anlagedatum         DATE        DEFAULT CURRENT_DATE NOT NULL,
    anlagevon           VARCHAR(30) DEFAULT USER         NOT NULL,
    aenderungsdatum     DATE,
    aenderungvon        VARCHAR(30),
    vngesamtzuwendung   NUMERIC(12, 2),
    sapinnenauftrag     VARCHAR(12),
    bpg_bauprogramm     NUMERIC(2, 0) REFERENCES fp_bauprogramme (bauprogramm),
    sgt_siedlungsgebiet NUMERIC(2, 0) REFERENCES fp_siedlungsgebiete (siedlungsgebiet),
    bauende             DATE,
    baubeendet          VARCHAR(1),
    bauvergabe1         DATE,
    baubeginn           DATE,
    baumitteilung       DATE,
    kreditnummer        NUMERIC(8, 0),
    stadtanleihe        VARCHAR(50),
    anleihenennwert     NUMERIC(9, 0),
    anleihejahrvon      NUMERIC(4, 0),
    anleihejahrbis      NUMERIC(4, 0)
);

CREATE INDEX ON fp_projekte (aenderungsdatum);
CREATE INDEX ON fp_projekte (bez_stadtbezirk);
CREATE INDEX ON fp_projekte (ble_bauleitung);
CREATE INDEX ON fp_projekte (bpg_bauprogramm);
CREATE INDEX ON fp_projekte (fob_fb);
CREATE INDEX ON fp_projekte (krn_krhname);
CREATE INDEX ON fp_projekte (kur_kurzbez);
CREATE INDEX ON fp_projekte (sgt_siedlungsgebiet);
CREATE INDEX ON fp_projekte (uas_ua);

COMMENT ON COLUMN fp_projekte.projnr IS 'Primary Key Projektnummer zusammengesetzt';
COMMENT ON COLUMN fp_projekte.fob_fb IS 'Förderbereich Kurzform';
COMMENT ON COLUMN fp_projekte.kur_kurzbez IS 'Kurzbezeichnung zur Klassifizierung eines Projekts';
COMMENT ON COLUMN fp_projekte.uas_ua IS 'Unterabschnitt als Teil der Projektnummer (Stelle 1-2)';
COMMENT ON COLUMN fp_projekte.jahr IS 'Jahreszahl zweistellig als Teil der Projektnummer (Stelle 3-4)';
COMMENT ON COLUMN fp_projekte.lfdnr1 IS 'Laufende Nummer einstellig als Teil der Projektnummer (Stelle 5)';
COMMENT ON COLUMN fp_projekte.lfdnr2 IS 'Laufende Nummer zweistellig als Teil der Projektnummer (Stelle 6-7)';
COMMENT ON COLUMN fp_projekte.pname IS 'Name des Projekts (altes Verfahren: beginnend mit der Straße)';
COMMENT ON COLUMN fp_projekte.pstrasse IS 'Straße des Projekts allein';
COMMENT ON COLUMN fp_projekte.kauf IS 'Liegt ein Ankauf oder Teilerwerb vor';
COMMENT ON COLUMN fp_projekte.projart IS 'Beschreibung des Projekts etwa Umbau, Neubau (Freitext)';
COMMENT ON COLUMN fp_projekte.refinanzierbar IS 'Ist dieses Förderprojekt refinanzierbar';
COMMENT ON COLUMN fp_projekte.ble_bauleitung IS 'Zuständige Abteilung im Baureferat (FK)';
COMMENT ON COLUMN fp_projekte.bauleitungkontakt IS 'Baustand: Name des Projektleiters sowie Telefon';
COMMENT ON COLUMN fp_projekte.bez_stadtbezirk IS 'Nummer des Stadtbezirks (FK)';
COMMENT ON COLUMN fp_projekte.krn_krhname IS 'Kurzbezeichnung Krankenhausname (FK)';
COMMENT ON COLUMN fp_projekte.krhzweck IS 'Förderung nach Jahreskrankenhausbauprogramm (Gültige Werte siehe FP_DOMAINS)';
COMMENT ON COLUMN fp_projekte.krisofp IS 'Art des Krippensonderförderprogramms (Gültige Werte siehe FP_DOMAINS)';
COMMENT ON COLUMN fp_projekte.kripplatz IS 'Anzahl der Krippenplätze';
COMMENT ON COLUMN fp_projekte.kigaplatz IS 'Anzahl der Kindergartenplätze';
COMMENT ON COLUMN fp_projekte.hortplatz IS 'Anzahl der Hortplätze';
COMMENT ON COLUMN fp_projekte.vndat IS 'Datum des abgeschlossenen Verwendungsnachweises.';
COMMENT ON COLUMN fp_projekte.vnkosten IS 'Endkosten lt. Verwendungsnachweis';
COMMENT ON COLUMN fp_projekte.vnzwfkosten IS 'Zuwendungsfähige Gesamtkosten lt. Verwendungsnachweis';
COMMENT ON COLUMN fp_projekte.vnpruefdat IS 'Datum der Prüfung des Verwendungsnachweises lt. Zuwendungsgeber';
COMMENT ON COLUMN fp_projekte.vnrueck_z IS 'Höhe des zurückgeforderten Zuschussbetrags  lt. Verwendungsnachweis';
COMMENT ON COLUMN fp_projekte.vnnachfoerderung IS 'Höhe der Nachförderung (Zuschuss)  lt. Verwendungsnachweis';
COMMENT ON COLUMN fp_projekte.vnpruefzwf IS 'Höhe der geprüften zuwendungsfähigen Kosten  lt. Verwendungsnachweis';
COMMENT ON COLUMN fp_projekte.vnschlusszwf IS 'Höhe der endgültigen zuwendungsfähigen Kosten  lt. Verwendungsnachweis';
COMMENT ON COLUMN fp_projekte.vnschlussbew IS 'Datum des letzten Bewilligungsbescheids (Schlussbescheid)  lt. Verwendungsnachweis';
COMMENT ON COLUMN fp_projekte.sap IS 'Wird dieses Projekt in SAP geführt';
COMMENT ON COLUMN fp_projekte.sapstatauf IS 'Statistischer Innenauftrag';
COMMENT ON COLUMN fp_projekte.sapmatnr IS 'SAP Materialnummer';
COMMENT ON COLUMN fp_projekte.sapwertnr IS 'SAP Wertkontraktnummer';
COMMENT ON COLUMN fp_projekte.sapjahrwert IS 'Datum in SAP (Jahr Wertkontrakt)';
COMMENT ON COLUMN fp_projekte.sapanlagennr IS 'SAP Anlagennummer';
COMMENT ON COLUMN fp_projekte.zinsen IS 'Höhe der Zinszahlungen';
COMMENT ON COLUMN fp_projekte.zinsdatum IS 'Datum der Zinszahlungen';
COMMENT ON COLUMN fp_projekte.fipo IS 'Finanzposition im Haushalt (Haushaltsstelle) für Zuwendungen';
COMMENT ON COLUMN fp_projekte.buchungskreis IS 'SAP Buchungskreis für Zuwendungen';
COMMENT ON COLUMN fp_projekte.sachkonto IS 'SAP Sachkonto für Zuwendungen';
COMMENT ON COLUMN fp_projekte.fipo_k IS 'Finanzposition im Haushalt (Haushaltsstelle) für Erstattungen';
COMMENT ON COLUMN fp_projekte.buchungskreis_k IS 'SAP Buchungskreis für Erstattungen';
COMMENT ON COLUMN fp_projekte.sachkonto_k IS 'SAP Sachkonto für Erstattungen';
COMMENT ON COLUMN fp_projekte.psbaubuch IS 'Projektstruktur Baubuchnummer Teil1';
COMMENT ON COLUMN fp_projekte.psbauref IS 'Projektstruktur Baubuchnummer Teil2  (Gültige Werte siehe FP_DOMAINS)';
COMMENT ON COLUMN fp_projekte.psbaunr IS 'Projektstruktur Baubuchnummer Teil3';
COMMENT ON COLUMN fp_projekte.notizen IS 'Notizen zum Projekt, Baustand und VN (Freitext)';
COMMENT ON COLUMN fp_projekte.altdaten IS 'Kennzeichen ob dieses Projekt aus der Altdatenübernahme stammt 0=nein, 1=ja';
COMMENT ON COLUMN fp_projekte.anlagedatum IS 'Dieser Satz wurde angelegt am';
COMMENT ON COLUMN fp_projekte.anlagevon IS 'Dieser Satz wurde angelegt von diesem Benutzer';
COMMENT ON COLUMN fp_projekte.aenderungsdatum IS 'Dieser Satz wurde zuletzt geändert am';
COMMENT ON COLUMN fp_projekte.aenderungvon IS 'Dieser Satz wurde zuletzt geändert von diesem Benutzer';
COMMENT ON COLUMN fp_projekte.vngesamtzuwendung IS 'Im Schlussbescheid festgesetzte Gesamtzuwendung seitens der Fördermittelgebers';
COMMENT ON COLUMN fp_projekte.sapinnenauftrag IS 'SAP Innenauftrag';
COMMENT ON COLUMN fp_projekte.bpg_bauprogramm IS 'Nummer des zugehörigen Bauprogramms (FK)';
COMMENT ON COLUMN fp_projekte.sgt_siedlungsgebiet IS 'Nummer des zugehörigen Siedlungsgebietes (FK)';
COMMENT ON COLUMN fp_projekte.bauende IS 'Datum des voraussichtlichen oder endgültigen Bauendes';
COMMENT ON COLUMN fp_projekte.baubeendet IS 'Status zum Datum des Bauendes (Gültige Werte siehe FP_DOMAINS)';
COMMENT ON COLUMN fp_projekte.bauvergabe1 IS 'Wann erfolgte die erste Vergabe zum Bau';
COMMENT ON COLUMN fp_projekte.baubeginn IS 'Wann erfolgte der offizielle Baubeginn';
COMMENT ON COLUMN fp_projekte.baumitteilung IS 'Wann erfolgte die letzte Mitteilung zum Bau';
COMMENT ON COLUMN fp_projekte.kreditnummer IS 'Kreditnummer von der Kämmerei vergeben';
COMMENT ON COLUMN fp_projekte.stadtanleihe IS 'Falls Stadtanleihe dann Beschreibung oder Titel der Stadtanleihe';
COMMENT ON COLUMN fp_projekte.anleihenennwert IS 'Höhe der Anleihe (Nominalwert)';
COMMENT ON COLUMN fp_projekte.anleihejahrvon IS 'Laufzeit der Anleihe (Jahr von)';
COMMENT ON COLUMN fp_projekte.anleihejahrbis IS 'Laufzeit der Anleihe (Jahr bis)';
COMMENT ON TABLE fp_projekte IS 'Alle Projekte der Fördermittelverwaltung (dbase:projekte,kindbetr,vn)';
--------------------------------------------------------
--  DDL for Table FP_ANTRAEGE
--------------------------------------------------------

CREATE TABLE fp_antraege
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_projnr      VARCHAR(7)                       NOT NULL REFERENCES fp_projekte (projnr),
    antragsdatum    DATE,
    antragstyp      VARCHAR(1)                       NOT NULL,
    geskosten       NUMERIC(10, 0)                   NOT NULL,
    zwfkosten       NUMERIC(10, 0)                   NOT NULL,
    vorzbeg         BOOLEAN     DEFAULT FALSE        NOT NULL,
    vbdatum         DATE,
    unbeddat        DATE,
    unbedja         DATE,
    unbedbis        DATE,
    a_su_z          NUMERIC(10, 0)                   NOT NULL,
    a_su_d          NUMERIC(10, 0)                   NOT NULL,
    a_su_k          NUMERIC(10, 0)                   NOT NULL,
    b_vor_su_z      NUMERIC(10, 0)                   NOT NULL,
    b_vor_su_d      NUMERIC(10, 0)                   NOT NULL,
    b_vor_su_k      NUMERIC(10, 0)                   NOT NULL,
    notizen         TEXT,
    anlagedatum     DATE        DEFAULT CURRENT_DATE NOT NULL,
    anlagevon       VARCHAR(30) DEFAULT USER         NOT NULL,
    aenderungsdatum DATE,
    aenderungvon    VARCHAR(30)
);

CREATE INDEX ON fp_antraege (pro_projnr);

COMMENT ON COLUMN fp_antraege.id IS 'Primärschlüssel eines Fördermittelantrags';
COMMENT ON COLUMN fp_antraege.pro_projnr IS 'Dieser Antrag bezieht sich auf dieses Projekt';
COMMENT ON COLUMN fp_antraege.antragsdatum IS 'Datum des Förderantrags';
COMMENT ON COLUMN fp_antraege.antragstyp IS 'Typ des Förderantrags  (Gültige Werte siehe FP_DOMAINS)';
COMMENT ON COLUMN fp_antraege.geskosten IS 'Beantragte Gesamtkosten des Projekts bei diesem Antrag (besonders beim Erstantrag)';
COMMENT ON COLUMN fp_antraege.zwfkosten IS 'Beantragte zuwendungsfähige Gesamtkosten bei diesem Antrag';
COMMENT ON COLUMN fp_antraege.vorzbeg IS 'Wurde Antrag auf vorzeitigen Baubeginn gestellt';
COMMENT ON COLUMN fp_antraege.vbdatum IS 'Datum eines vorzeitigen Baubeginns';
COMMENT ON COLUMN fp_antraege.unbeddat IS 'Datum des Antrags auf Unbedenklichkeit';
COMMENT ON COLUMN fp_antraege.unbedja IS 'Datum der erteilten Unbedenklichkeitsbescheinigung';
COMMENT ON COLUMN fp_antraege.unbedbis IS 'Die erteilte Unbedenklichkeitsbescheinigung ist gültig bis zu diesem Datum';
COMMENT ON COLUMN fp_antraege.a_su_z IS 'Höhe des beantragten Zuschusses (nur Anteil für ein Jahr)';
COMMENT ON COLUMN fp_antraege.a_su_d IS 'Höhe des beantragten Darlehens (nur Anteil für ein Jahr)';
COMMENT ON COLUMN fp_antraege.a_su_k IS 'Höhe der beantragten Kostenerstattung (Konnexität, nur Anteil für ein Jahr)';
COMMENT ON COLUMN fp_antraege.b_vor_su_z IS 'voraussichtlich bewilligte Gesamtzuwendung';
COMMENT ON COLUMN fp_antraege.b_vor_su_d IS 'voraussichtlich bewilligtes Gesamtdarlehen';
COMMENT ON COLUMN fp_antraege.b_vor_su_k IS ' voraussichtlich bewilligte Kostenerstattung';
COMMENT ON COLUMN fp_antraege.notizen IS 'Notizen zu einem Antrag als Freitext';
COMMENT ON COLUMN fp_antraege.anlagedatum IS 'Dieser Satz wurde angelegt am';
COMMENT ON COLUMN fp_antraege.anlagevon IS 'Dieser Satz wurde angelegt von diesem Benutzer';
COMMENT ON COLUMN fp_antraege.aenderungsdatum IS 'Dieser Satz wurde zuletzt geändert am';
COMMENT ON COLUMN fp_antraege.aenderungvon IS 'Dieser Satz wurde zuletzt geändert von diesem Benutzer';
COMMENT ON TABLE fp_antraege IS 'Enthält alle Förderanträge zu Projekten ((dbase:erstantr)';
--------------------------------------------------------
--  DDL for Table FP_BEWILLIGUNGEN
--------------------------------------------------------

CREATE TABLE fp_bewilligungen
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_projnr      VARCHAR(7)                       NOT NULL REFERENCES fp_projekte (projnr),
    ant_id          BIGINT REFERENCES fp_antraege (id),
    bdatum          DATE,
    afsatz          NUMERIC(8, 2)                    NOT NULL,
    bfsatz          NUMERIC(8, 2)                    NOT NULL,
    bzwfkosten      NUMERIC(10, 0)                   NOT NULL,
    bzuwendung_z    NUMERIC(10, 0),
    bzuwendung_d    NUMERIC(10, 0),
    bzuwendung_k    NUMERIC(10, 0),
    bzuwart         VARCHAR(1),
    baktenzeichen   VARCHAR(20),
    geszuwendungen  NUMERIC(10, 0)                   NOT NULL,
    geskonnex       NUMERIC(10, 0)                   NOT NULL,
    krw             VARCHAR(1),
    notizen         TEXT,
    anlagedatum     DATE        DEFAULT CURRENT_DATE NOT NULL,
    anlagevon       VARCHAR(30) DEFAULT USER         NOT NULL,
    aenderungsdatum DATE,
    aenderungvon    VARCHAR(30)
);

CREATE INDEX ON fp_bewilligungen (ant_id);
CREATE INDEX ON fp_bewilligungen (pro_projnr);

COMMENT ON COLUMN fp_bewilligungen.id IS 'Primärschlüssel einer Bewilligung';
COMMENT ON COLUMN fp_bewilligungen.pro_projnr IS 'Diese Bewilligung bezieht sich auf dieses Projekt';
COMMENT ON COLUMN fp_bewilligungen.ant_id IS 'Diese Bewilligung bezieht sich auf einen Antrag';
COMMENT ON COLUMN fp_bewilligungen.bdatum IS 'Datum der Bewilligung';
COMMENT ON COLUMN fp_bewilligungen.afsatz IS 'Beantrager Fördersatz';
COMMENT ON COLUMN fp_bewilligungen.bfsatz IS 'Bewilligter Fördersatz';
COMMENT ON COLUMN fp_bewilligungen.bzwfkosten IS 'bewilligte zuwendungsfähige Kosten Gesamtbetrag';
COMMENT ON COLUMN fp_bewilligungen.bzuwendung_z IS 'Bewilligte Zuwendung auf Jahresbasis als Zuschuss';
COMMENT ON COLUMN fp_bewilligungen.bzuwendung_d IS 'Bewilligte Zuwendung auf Jahresbasis als Darlehen';
COMMENT ON COLUMN fp_bewilligungen.bzuwendung_k IS 'Bewilligte Zuwendung auf Jahresbasis als Kostenerstattung';
COMMENT ON COLUMN fp_bewilligungen.bzuwart IS 'Bewilligte Zuwendungsart (Werte siehe FP_DOMAINS)';
COMMENT ON COLUMN fp_bewilligungen.baktenzeichen IS 'Aktenzeichen des Bewilligers';
COMMENT ON COLUMN fp_bewilligungen.geszuwendungen IS 'Höhe der zu erwartenden Gesamtzuwendungen für das Förderprojekt zum Zeitpunkt dieser Bewilligung';
COMMENT ON COLUMN fp_bewilligungen.geskonnex IS 'Höhe der zu erwartenden Gesamtkonnexitätszahlungen für das Förderprojekt zum Zeitpunkt dieser Bewilligung';
COMMENT ON COLUMN fp_bewilligungen.krw IS 'Typ des Kostenrichtwerts (Werte siehe FP_DOMAINS)';
COMMENT ON COLUMN fp_bewilligungen.notizen IS 'Notizen zu einer Bewilligung als Freitext';
COMMENT ON COLUMN fp_bewilligungen.anlagedatum IS 'Dieser Satz wurde angelegt am';
COMMENT ON COLUMN fp_bewilligungen.anlagevon IS 'Dieser Satz wurde angelegt von diesem Benutzer';
COMMENT ON COLUMN fp_bewilligungen.aenderungsdatum IS 'Dieser Satz wurde zuletzt geändert am';
COMMENT ON COLUMN fp_bewilligungen.aenderungvon IS 'Dieser Satz wurde zuletzt geändert von diesem Benutzer';
COMMENT ON TABLE fp_bewilligungen IS 'Enthält alle Bewilligungen zu Förderanträgen. (dbase:bewill)';
--------------------------------------------------------
--  DDL for Table FP_ABRUFE
--------------------------------------------------------

CREATE TABLE fp_abrufe
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_projnr         VARCHAR(7)                       NOT NULL REFERENCES fp_projekte (projnr),
    bwi_id             BIGINT REFERENCES fp_bewilligungen (id),
    vnabr              VARCHAR(1),
    abruf_z            NUMERIC(10, 0)                   NOT NULL,
    abruf_d            NUMERIC(10, 0)                   NOT NULL,
    abruf_k            NUMERIC(10, 0)                   NOT NULL,
    abruf_datum        DATE,
    erh_z              NUMERIC(10, 0)                   NOT NULL,
    erh_d              NUMERIC(10, 0)                   NOT NULL,
    erh_k              NUMERIC(10, 0)                   NOT NULL,
    erh_datum          DATE,
    ref_refnr          NUMERIC(2, 0) REFERENCES fp_referate (refnr),
    sapabrufauftragsnr NUMERIC(8, 0),
    sapfakturanr       NUMERIC(10, 0),
    fipo               VARCHAR(15),
    buchungskreis      VARCHAR(4),
    sachkonto          VARCHAR(6),
    fipo_k             VARCHAR(15),
    buchungskreis_k    VARCHAR(4),
    sachkonto_k        VARCHAR(6),
    notizen            TEXT,
    anlagedatum        DATE        DEFAULT CURRENT_DATE NOT NULL,
    anlagevon          VARCHAR(30) DEFAULT USER         NOT NULL,
    aenderungsdatum    DATE,
    aenderungvon       VARCHAR(30)
);

CREATE INDEX ON fp_abrufe (bwi_id);
CREATE INDEX ON fp_abrufe (pro_projnr);
CREATE INDEX ON fp_abrufe (ref_refnr);

COMMENT ON COLUMN fp_abrufe.id IS 'Primärschlüssel eines Abrufs';
COMMENT ON COLUMN fp_abrufe.pro_projnr IS 'Dieser Abruf bezieht sich auf dieses Projekt';
COMMENT ON COLUMN fp_abrufe.bwi_id IS 'Dieser Abruf bezieht sich auf eine Bewilligung';
COMMENT ON COLUMN fp_abrufe.vnabr IS 'Ist der Abruf mit dem Verwendungsnachweis erfolgt (Gültige Werte siehe FP_DOMAINS)';
COMMENT ON COLUMN fp_abrufe.abruf_z IS 'Höhe der abgerufenen Zuwendung';
COMMENT ON COLUMN fp_abrufe.abruf_d IS 'Höhe des abgerufenen Darlehens';
COMMENT ON COLUMN fp_abrufe.abruf_k IS 'Höhe des abgerufenen Konnexitätsbetrags (Kostenerstattung)';
COMMENT ON COLUMN fp_abrufe.abruf_datum IS 'Datum an dem der Abruf erfolgte';
COMMENT ON COLUMN fp_abrufe.erh_z IS 'Höhe der erhaltenen Zuwendung';
COMMENT ON COLUMN fp_abrufe.erh_d IS 'Höhe des erhaltenen Darlehens';
COMMENT ON COLUMN fp_abrufe.erh_k IS 'Höhe der erhaltenen Konnexität (Kostenerstattung)';
COMMENT ON COLUMN fp_abrufe.erh_datum IS 'Datum des Geldeingangs';
COMMENT ON COLUMN fp_abrufe.ref_refnr IS 'Nummer des betroffenen Referats für diesen Abruf';
COMMENT ON COLUMN fp_abrufe.sapabrufauftragsnr IS 'SAP Auftragsnummer für diesen Abruf';
COMMENT ON COLUMN fp_abrufe.sapfakturanr IS 'SAP Fakturanummer für diesen Abruf';
COMMENT ON COLUMN fp_abrufe.fipo IS 'Haushaltsstelle (FIPO) für Zuwendungen für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN fp_abrufe.buchungskreis IS 'SAP Buchungskreis für Zuwendungen  für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN fp_abrufe.sachkonto IS 'SAP Sachkonto für Zuwendungen  für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN fp_abrufe.fipo_k IS 'Haushaltsstelle (FIPO) für Kostenerstattungen  für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN fp_abrufe.buchungskreis_k IS 'SAP Buchungskreis für Kostenerstattungen  für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN fp_abrufe.sachkonto_k IS 'SAP Sachkonto für Kostenerstattungen  für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN fp_abrufe.notizen IS 'Notizen zum Abruf als Freitext';
COMMENT ON COLUMN fp_abrufe.anlagedatum IS 'Dieser Satz wurde angelegt am';
COMMENT ON COLUMN fp_abrufe.anlagevon IS 'Dieser Satz wurde angelegt von diesem Benutzer';
COMMENT ON COLUMN fp_abrufe.aenderungsdatum IS 'Dieser Satz wurde zuletzt geändert am';
COMMENT ON COLUMN fp_abrufe.aenderungvon IS 'Dieser Satz wurde zuletzt geändert von diesem Benutzer';
COMMENT ON TABLE fp_abrufe IS 'Enthält die Abrufe zu den Bewilligungen eines Projekts (dbase:abrufe)';
--------------------------------------------------------
--  DDL for Table FP_ARCHIV
--------------------------------------------------------

CREATE TABLE fp_archiv
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_projnr         VARCHAR(7) REFERENCES fp_projekte (projnr),
    speicherdatum      DATE,
    speicherakt        BOOLEAN DEFAULT FALSE NOT NULL,
    speicherrechnungen BOOLEAN DEFAULT FALSE NOT NULL,
    mikrodatplan       DATE,
    mikrodat           DATE,
    notizen            TEXT
);

CREATE INDEX ON fp_archiv (pro_projnr);

COMMENT ON COLUMN fp_archiv.id IS 'Eindeutiger Schlüssel in der Tabelle';
COMMENT ON COLUMN fp_archiv.pro_projnr IS 'Die Ablage kann eine Projektablage sein';
COMMENT ON COLUMN fp_archiv.speicherdatum IS 'Datum der Ablage im Speicher';
COMMENT ON COLUMN fp_archiv.speicherakt IS 'Befindet sich auch der Akt zu einem Projekt im Speicher (0,1)';
COMMENT ON COLUMN fp_archiv.speicherrechnungen IS 'Befinden sich auch die Rechnungen zu einem Projekt im Speicher (0,1)';
COMMENT ON COLUMN fp_archiv.mikrodatplan IS 'Bestelldatum der Microfiche (neu: Feb 2013)';
COMMENT ON COLUMN fp_archiv.mikrodat IS 'Datum an dem die Microfiche erhalten und eingelagert wurden (neu: Feb 2013)';
COMMENT ON COLUMN fp_archiv.notizen IS 'Notizen als Freitext zu einer Ablage';
COMMENT ON TABLE fp_archiv IS 'Beschreibt welche allgemeinen Dokumente und Projektakten und Mikrofiche im Archiv liegen. Diese Ablagen können projektbezogen sein, aber auch Dokumente allgemeiner Natur. Das Archiv selbst befindet sich im Speicher des Rathauses (dbase: speicher und mik)';
--------------------------------------------------------
--  DDL for Table FP_BENUTZERHINWEISE
--------------------------------------------------------

CREATE TABLE fp_benutzerhinweise
(
    for_formsmodul VARCHAR(30) PRIMARY KEY,
    hinweis1       TEXT,
    hinweis2       TEXT,
    hinweis3       TEXT,
    menuetop       VARCHAR(40),
    menuezeile     VARCHAR(40)
);

COMMENT ON COLUMN fp_benutzerhinweise.for_formsmodul IS 'Name des Formsmoduls für den Bedienerhinweis';
COMMENT ON COLUMN fp_benutzerhinweise.hinweis1 IS 'Texte für Benutzerhilfen';
COMMENT ON COLUMN fp_benutzerhinweise.hinweis2 IS 'Texte für Benutzerhilfen';
COMMENT ON COLUMN fp_benutzerhinweise.hinweis3 IS 'Texte für Benutzerhilfen';
COMMENT ON COLUMN fp_benutzerhinweise.menuetop IS 'Menütext im Topmenü (etwa Projekte)';
COMMENT ON COLUMN fp_benutzerhinweise.menuezeile IS 'Menütext im aufrufenden Menü (etwa Bericht Zinsen)';
COMMENT ON TABLE fp_benutzerhinweise IS 'Enthält Benutzerhinweise im Kontext eines Forms Moduls und dient damit als online Benutzerhilfe';
--------------------------------------------------------
--  DDL for Table FP_DOMAINS
--------------------------------------------------------

CREATE TABLE fp_domains
(
    tabelle      VARCHAR(30) NOT NULL,
    spalte       VARCHAR(30) NOT NULL,
    wert         VARCHAR(3)  NOT NULL,
    beschreibung VARCHAR(50) NOT NULL,
    PRIMARY KEY (tabelle, spalte, wert)
);

COMMENT ON COLUMN fp_domains.tabelle IS 'Tabelle auf welche sich die Domäne bezieht';
COMMENT ON COLUMN fp_domains.spalte IS 'Spalte auf welche sich die Domäne bezieht';
COMMENT ON COLUMN fp_domains.wert IS 'Wert der Domäne';
COMMENT ON COLUMN fp_domains.beschreibung IS 'Beschreibung der Domäne';
COMMENT ON TABLE fp_domains IS 'Aufstellung aller Domains und ihrer Werte';
--------------------------------------------------------
--  DDL for Table FP_PUBLIKATIONEN
--------------------------------------------------------

CREATE TABLE fp_publikationen
(
    kurzform    VARCHAR(1) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN fp_publikationen.kurzform IS 'Kurzform der EU nahen Publikation';
COMMENT ON COLUMN fp_publikationen.bezeichnung IS 'Beschreibung der EU nahen Publikation';
COMMENT ON TABLE fp_publikationen IS 'Enthält Kurzformen EU naher Publikationen';
--------------------------------------------------------
--  DDL for Table FP_EUINFORMATIONEN
--------------------------------------------------------

CREATE TABLE fp_euinformationen
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jahr         NUMERIC(4, 0)         NOT NULL,
    pub_kurzform VARCHAR(1)            NOT NULL REFERENCES fp_publikationen (kurzform),
    hefta        VARCHAR(1),
    nummer       NUMERIC(3, 0)         NOT NULL,
    wichtig      BOOLEAN DEFAULT FALSE NOT NULL,
    seitennr     VARCHAR(3),
    stichwort    VARCHAR(50),
    rawi         BOOLEAN DEFAULT FALSE NOT NULL,
    schulref     BOOLEAN DEFAULT FALSE NOT NULL,
    sozref_r_5   BOOLEAN DEFAULT FALSE NOT NULL,
    rgu_11       BOOLEAN DEFAULT FALSE NOT NULL,
    rgu_cs       BOOLEAN DEFAULT FALSE NOT NULL,
    krh          BOOLEAN DEFAULT FALSE NOT NULL,
    afa          BOOLEAN DEFAULT FALSE NOT NULL,
    swm          BOOLEAN DEFAULT FALSE NOT NULL,
    kulturref    BOOLEAN DEFAULT FALSE NOT NULL,
    bauref       BOOLEAN DEFAULT FALSE NOT NULL,
    planref      BOOLEAN DEFAULT FALSE NOT NULL,
    direktorium  BOOLEAN DEFAULT FALSE NOT NULL,
    por          BOOLEAN DEFAULT FALSE NOT NULL,
    kvr          BOOLEAN DEFAULT FALSE NOT NULL,
    kommref      BOOLEAN DEFAULT FALSE NOT NULL,
    sew          BOOLEAN DEFAULT FALSE NOT NULL,
    stk          BOOLEAN DEFAULT FALSE NOT NULL,
    inhalt       VARCHAR(200)          NOT NULL,
    infodat      DATE
);

COMMENT ON COLUMN fp_euinformationen.id IS 'Primary Key';
COMMENT ON COLUMN fp_euinformationen.jahr IS 'Jahr der Erscheinung';
COMMENT ON COLUMN fp_euinformationen.pub_kurzform IS 'Publikation';
COMMENT ON COLUMN fp_euinformationen.hefta IS 'Zusatzbezeichnung zur Publikation';
COMMENT ON COLUMN fp_euinformationen.nummer IS 'Nummer des Heftes';
COMMENT ON COLUMN fp_euinformationen.wichtig IS 'Information weitergeben';
COMMENT ON COLUMN fp_euinformationen.seitennr IS 'Seitennummer inerhalb des Heftes';
COMMENT ON COLUMN fp_euinformationen.stichwort IS 'Stichwort zu dieser Infomation';
COMMENT ON COLUMN fp_euinformationen.rawi IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.schulref IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.sozref_r_5 IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.rgu_11 IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.rgu_cs IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.krh IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.afa IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.swm IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.kulturref IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.bauref IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.planref IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.direktorium IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.por IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.kvr IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.kommref IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.sew IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.stk IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN fp_euinformationen.inhalt IS 'Kurzbeschreibung der Information';
COMMENT ON COLUMN fp_euinformationen.infodat IS 'Datum der Information';
COMMENT ON TABLE fp_euinformationen IS 'Enthält wesentliche Informationen diverses EU-naher Publikationen und ist Basis einer eigenständigen Applikation (dbase:eu)';
--------------------------------------------------------
--  DDL for Table FP_GEPLANTEMASSNAHMEN
--------------------------------------------------------

CREATE TABLE fp_geplantemassnahmen
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kur_kurzbez     VARCHAR(8) NOT NULL REFERENCES fp_kurzbezeichnungen (kurzbez),
    bez_stadtbezirk NUMERIC(2, 0) REFERENCES fp_stadtbezirke (stadtbezirk),
    strasse         VARCHAR(50),
    projekt         VARCHAR(70),
    baubeginn       NUMERIC(4, 0),
    angelegt        NUMERIC(4, 0),
    plannr          VARCHAR(10)
);

COMMENT ON COLUMN fp_geplantemassnahmen.id IS 'Primary Key';
COMMENT ON COLUMN fp_geplantemassnahmen.kur_kurzbez IS 'Kurzform der Projektkategorie für das Vorhaben';
COMMENT ON COLUMN fp_geplantemassnahmen.bez_stadtbezirk IS 'Stadtbezirk der geplanten Maßnahme';
COMMENT ON COLUMN fp_geplantemassnahmen.strasse IS 'Strasse des Vorhabens';
COMMENT ON COLUMN fp_geplantemassnahmen.projekt IS 'Projektbezeichnung';
COMMENT ON COLUMN fp_geplantemassnahmen.baubeginn IS 'Geplanter Baubeginn (Jahr)';
COMMENT ON COLUMN fp_geplantemassnahmen.angelegt IS 'Vorgang angelegt (Jahr)';
COMMENT ON COLUMN fp_geplantemassnahmen.plannr IS 'Nummer des Bebauungsplans';
COMMENT ON TABLE fp_geplantemassnahmen IS 'Enthält Infomationen über zukünftige, geplanten Maßnahmen die mal in Projekte münden sollen (dbase:geplmasn)';
--------------------------------------------------------
--  DDL for Table FP_HHJAHRE
--------------------------------------------------------

CREATE TABLE fp_hhjahre
(
    hhjahr        NUMERIC(4, 0) PRIMARY KEY,
    hhbezeichnung VARCHAR(200) NOT NULL,
    notizen       TEXT
);

COMMENT ON COLUMN fp_hhjahre.hhjahr IS 'Haushaltsjahr';
COMMENT ON COLUMN fp_hhjahre.hhbezeichnung IS 'Bezeichnung des Haushaltsjahres';
COMMENT ON COLUMN fp_hhjahre.notizen IS 'Notizen und Protokoll zu einem Haushaltsjahr';
COMMENT ON TABLE fp_hhjahre IS 'Aufstellung aller Haushaltsjahre';
--------------------------------------------------------
--  DDL for Table FP_HHPLAN
--------------------------------------------------------

CREATE TABLE fp_hhplan
(
    hhj_jahr          NUMERIC(4, 0)                         NOT NULL REFERENCES fp_hhjahre (hhjahr),
    fipo              VARCHAR(15) DEFAULT '000000000000000' NOT NULL,
    pro_projnr        VARCHAR(7)                            NOT NULL REFERENCES fp_projekte (projnr),
    p_pstrasse        VARCHAR(100),
    p_pname           VARCHAR(100),
    p_fob_fb          NUMERIC(2, 0),
    p_bez_stadtbezirk NUMERIC(2, 0),
    p_lna_kurzbez     VARCHAR(3),
    p_vndat           DATE,
    mitteleinplanung  NUMERIC(12, 0),
    bewilligung_voj   NUMERIC(12, 0),
    bewilligung_hhj   NUMERIC(12, 0),
    erhalten_voj      NUMERIC(12, 0),
    erhalten_hhj      NUMERIC(12, 0),
    baustandaktuell   NUMERIC(12, 2),
    an                NUMERIC(12, 0),
    n1                NUMERIC(12, 0),
    n2                NUMERIC(12, 0),
    notizen           TEXT,
    anlagedatum       DATE        DEFAULT CURRENT_DATE      NOT NULL,
    anlagevon         VARCHAR(30) DEFAULT USER              NOT NULL,
    aenderungsdatum   DATE,
    aenderungvon      VARCHAR(30),
    PRIMARY KEY (hhj_jahr, pro_projnr)
);

CREATE INDEX ON fp_hhplan (pro_projnr);

COMMENT ON COLUMN fp_hhplan.hhj_jahr IS 'Planung für ein Haushaltsjahr';
COMMENT ON COLUMN fp_hhplan.fipo IS 'Planung für eine FIPO (Haushaltsstelle) des Projekts (Zuwendungen oder Konnexität)';
COMMENT ON COLUMN fp_hhplan.pro_projnr IS 'Planung für ein Projekt innerhalb eines Haushaltsjahres';
COMMENT ON COLUMN fp_hhplan.p_pstrasse IS 'Strasse aus Projekt übernommen';
COMMENT ON COLUMN fp_hhplan.p_pname IS 'Projektname aus Projekt übernommen';
COMMENT ON COLUMN fp_hhplan.p_fob_fb IS 'Förderbereich aus Projekt übernommen';
COMMENT ON COLUMN fp_hhplan.p_bez_stadtbezirk IS 'Stadtbezirk aus Projekt übernommen';
COMMENT ON COLUMN fp_hhplan.p_lna_kurzbez IS 'Bezirksliste übernommen';
COMMENT ON COLUMN fp_hhplan.p_vndat IS 'VN Datum aus Projekt übernommen';
COMMENT ON COLUMN fp_hhplan.mitteleinplanung IS 'Mitteleinplanung zum Zeitpunkt der Erstellung der Planung.';
COMMENT ON COLUMN fp_hhplan.bewilligung_voj IS 'Bewilligte Zuwendungen in den Vorjahren.';
COMMENT ON COLUMN fp_hhplan.bewilligung_hhj IS 'Bewilligte Zuwendungen im Haushaltsjahr.';
COMMENT ON COLUMN fp_hhplan.erhalten_voj IS 'Erhaltene Zuwendungen in den Vorjahren.';
COMMENT ON COLUMN fp_hhplan.erhalten_hhj IS 'Erhaltene Zuwendungen im Haushaltsjahr.';
COMMENT ON COLUMN fp_hhplan.baustandaktuell IS 'Baustand zum Zeitpunkt der Erstellung der Planung.';
COMMENT ON COLUMN fp_hhplan.an IS 'Ansatz im Nov des Vorjahres. Wird manuell erfasst.';
COMMENT ON COLUMN fp_hhplan.n1 IS '1. Nachtrag im April des Haushaltsjahres. Wird manuell erfasst.';
COMMENT ON COLUMN fp_hhplan.n2 IS '2. Nachtrag im August des Haushaltsjahres. Wird manuell erfasst.';
COMMENT ON COLUMN fp_hhplan.notizen IS 'Notizen und Anmerkungen bezüglich einer Position im Haushaltsplan';
COMMENT ON COLUMN fp_hhplan.anlagedatum IS 'Dieser Satz wurde angelegt am';
COMMENT ON COLUMN fp_hhplan.anlagevon IS 'Dieser Satz wurde angelegt von diesem Benutzer';
COMMENT ON COLUMN fp_hhplan.aenderungsdatum IS 'Dieser Satz wurde zuletzt geändert am';
COMMENT ON COLUMN fp_hhplan.aenderungvon IS 'Dieser Satz wurde zuletzt geändert von diesem Benutzer';
COMMENT ON TABLE fp_hhplan IS 'Enthält Einnahmen (Zuwendungen und Kostenerstattungen) je Projekt und Jahr und FIPO. Ist Basis für die jährliche Aufstellung der Haushaltsplanung (dbase:haush)';
--------------------------------------------------------
--  DDL for Table FP_JAHRESSTATISTIK
--------------------------------------------------------

CREATE TABLE fp_jahresstatistik
(
    jahr                 NUMERIC(4, 0) PRIMARY KEY,
    jahresstatistik1_am  DATE,
    jahresstatistik1_von VARCHAR(30),
    jahresstatistik2_am  DATE,
    jahresstatistik2_von VARCHAR(30),
    jahresstatistik3_am  DATE,
    jahresstatistik3_von VARCHAR(30),
    notizen              TEXT
);

COMMENT ON COLUMN fp_jahresstatistik.jahr IS 'Jahr der Statistik';
COMMENT ON COLUMN fp_jahresstatistik.jahresstatistik1_am IS 'Die Jahresstatistik I wurde zuletzt zu diesem Zeitpunkt erstellt';
COMMENT ON COLUMN fp_jahresstatistik.jahresstatistik1_von IS 'Die Jahresstatistik I wurde zuletzt von diesem Benutzer erstellt';
COMMENT ON COLUMN fp_jahresstatistik.jahresstatistik2_am IS 'Die Jahresstatistik II wurde zuletzt zu diesem Zeitpunkt erstellt';
COMMENT ON COLUMN fp_jahresstatistik.jahresstatistik2_von IS 'Die Jahresstatistik II wurde zuletzt von diesem Benutzer erstellt';
COMMENT ON COLUMN fp_jahresstatistik.jahresstatistik3_am IS 'Die Jahresstatistik III wurde zuletzt zu diesem Zeitpunkt erstellt';
COMMENT ON COLUMN fp_jahresstatistik.jahresstatistik3_von IS 'Die Jahresstatistik III wurde zuletzt von diesem Benutzer erstellt';
COMMENT ON COLUMN fp_jahresstatistik.notizen IS 'Allgemeine Notizen';
COMMENT ON TABLE fp_jahresstatistik IS 'Diese Tabelle protokolliert die Erstellung der drei Jahresstatistiken';
--------------------------------------------------------
--  DDL for Table FP_JAHRESSTATISTIK1
--------------------------------------------------------

CREATE TABLE fp_jahresstatistik1
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jss_jahr         NUMERIC(4, 0) NOT NULL REFERENCES fp_jahresstatistik (jahr),
    foerderbereich   VARCHAR(60)   NOT NULL,
    fb               NUMERIC(2, 0) NOT NULL,
    gruppe           NUMERIC(1, 0) NOT NULL,
    gesamtkosten     NUMERIC(12, 2),
    zuwendungsfaehig NUMERIC(12, 2),
    b_zuschuss       NUMERIC(12, 2),
    b_darlehen       NUMERIC(12, 2),
    b_konnexitaet    NUMERIC(12, 2),
    e_zuschuss       NUMERIC(12, 2),
    e_darlehen       NUMERIC(12, 2),
    e_konnexitaet    NUMERIC(12, 2)
);

COMMENT ON COLUMN fp_jahresstatistik1.id IS 'ID als Sortierungskriterium';
COMMENT ON COLUMN fp_jahresstatistik1.jss_jahr IS 'Jahr der Statistik';
COMMENT ON COLUMN fp_jahresstatistik1.foerderbereich IS 'Beschreibung des Förderbereichs';
COMMENT ON COLUMN fp_jahresstatistik1.fb IS 'Nummer des Förderbereichs';
COMMENT ON COLUMN fp_jahresstatistik1.gruppe IS 'Gruppenkennzeichen (1) FAG ohne KIGA  (2) FAG KIGA  (3) alle anderen FB  für Zwischensummen';
COMMENT ON COLUMN fp_jahresstatistik1.gesamtkosten IS 'Gesamtkosten im Erstantrag';
COMMENT ON COLUMN fp_jahresstatistik1.zuwendungsfaehig IS 'Zuwendungsfähige Kosten im Erstantrag';
COMMENT ON COLUMN fp_jahresstatistik1.b_zuschuss IS 'Bewilligter Zuschuss  im Jahr';
COMMENT ON COLUMN fp_jahresstatistik1.b_darlehen IS 'Bewilligtes Darlehen  im Jahr';
COMMENT ON COLUMN fp_jahresstatistik1.b_konnexitaet IS 'Bewilligte Konnexität im Jahr';
COMMENT ON COLUMN fp_jahresstatistik1.e_zuschuss IS 'Erhaltener Zuschuss  im Jahr';
COMMENT ON COLUMN fp_jahresstatistik1.e_darlehen IS 'Erhaltenes Darlehen  im Jahr';
COMMENT ON COLUMN fp_jahresstatistik1.e_konnexitaet IS 'Erhaltene Konnexität im Jahr';
COMMENT ON TABLE fp_jahresstatistik1 IS 'Diese Tabelle enthält die generierte Jahresstatistik für Seite I';
--------------------------------------------------------
--  DDL for Table FP_JAHRESSTATISTIK2
--------------------------------------------------------

CREATE TABLE fp_jahresstatistik2
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jss_jahr             NUMERIC(4, 0) NOT NULL REFERENCES fp_jahresstatistik (jahr),
    foerderbereich       VARCHAR(60)   NOT NULL,
    fb                   NUMERIC(2, 0) NOT NULL,
    gruppe               NUMERIC(1, 0) NOT NULL,
    anzahl_abrufe        NUMERIC(10, 0),
    anzahl_vn            NUMERIC(10, 0),
    anzahl_bewilligungen NUMERIC(10, 0),
    vngeskosten          NUMERIC(12, 2),
    anzahl_erst          NUMERIC(10, 0),
    a_su_z_erst          NUMERIC(12, 2),
    a_su_k_erst          NUMERIC(12, 2),
    anzahl_folge         NUMERIC(10, 0),
    a_su_z_folge         NUMERIC(12, 2),
    a_su_k_folge         NUMERIC(12, 2),
    a_vor_su_z_gesamt    NUMERIC(12, 2),
    a_vor_su_k_gesamt    NUMERIC(12, 2),
    anzahl_unbed         NUMERIC(10, 0)
);

COMMENT ON COLUMN fp_jahresstatistik2.id IS 'ID als Sortierkriterium';
COMMENT ON COLUMN fp_jahresstatistik2.jss_jahr IS 'Jahr der Statistik';
COMMENT ON COLUMN fp_jahresstatistik2.foerderbereich IS 'Beschreibung des Förderbereichs';
COMMENT ON COLUMN fp_jahresstatistik2.fb IS 'Nummer des Förderbereichs';
COMMENT ON COLUMN fp_jahresstatistik2.gruppe IS 'Gruppenkennzeichen für Zwischensummen';
COMMENT ON COLUMN fp_jahresstatistik2.anzahl_abrufe IS 'Anzahl der Abrufe eines Jahres';
COMMENT ON COLUMN fp_jahresstatistik2.anzahl_vn IS 'Anzahl der Verwendungsnachweise eines Jahres';
COMMENT ON COLUMN fp_jahresstatistik2.anzahl_bewilligungen IS 'Anzahl der Bewilligungen eines Jahres';
COMMENT ON COLUMN fp_jahresstatistik2.vngeskosten IS 'Endkosten im Verwendungsnachweis';
COMMENT ON COLUMN fp_jahresstatistik2.anzahl_erst IS 'Anzahl der Erstanträge eines Jahres';
COMMENT ON COLUMN fp_jahresstatistik2.a_su_z_erst IS 'Zuwendungen bei Erstanträgen in einem Jahr';
COMMENT ON COLUMN fp_jahresstatistik2.a_su_k_erst IS 'Konnexität bei Erstanträgen in einem Jahr';
COMMENT ON COLUMN fp_jahresstatistik2.anzahl_folge IS 'Anzahl der Folgeanträge eines Jahres';
COMMENT ON COLUMN fp_jahresstatistik2.a_su_z_folge IS 'Zuwendungen bei Folgeanträgen in einem Jahr';
COMMENT ON COLUMN fp_jahresstatistik2.a_su_k_folge IS 'Konnexität bei Folgeanträgen in einem Jahr';
COMMENT ON COLUMN fp_jahresstatistik2.a_vor_su_z_gesamt IS 'Voraussichtliche Gesamtzuwendung über alle Anträge eines Jahres';
COMMENT ON COLUMN fp_jahresstatistik2.a_vor_su_k_gesamt IS 'Voraussichtliche Gesamtkonnexität über alle Anträge eines Jahres';
COMMENT ON COLUMN fp_jahresstatistik2.anzahl_unbed IS 'Anzahl der Unbedenklichkeitsanträge eines Jahres';
COMMENT ON TABLE fp_jahresstatistik2 IS 'Diese Tabelle enthält die generierte Jahresstatistik für Seite II';
--------------------------------------------------------
--  DDL for Table FP_JAHRESSTATISTIK3
--------------------------------------------------------

CREATE TABLE fp_jahresstatistik3
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jss_jahr           NUMERIC(4, 0) NOT NULL REFERENCES fp_jahresstatistik (jahr),
    foerderbereich     VARCHAR(60)   NOT NULL,
    fb                 NUMERIC(2, 0) NOT NULL,
    gruppe             NUMERIC(1, 0) NOT NULL,
    bzuwendung_z_plus  NUMERIC(12, 2),
    bzuwendung_z_minus NUMERIC(12, 2),
    bzuwendung_d_plus  NUMERIC(12, 2),
    bzuwendung_d_minus NUMERIC(12, 2),
    bzuwendung_k_plus  NUMERIC(12, 2),
    bzuwendung_k_minus NUMERIC(12, 2),
    erh_z              NUMERIC(12, 2),
    erh_d              NUMERIC(12, 2),
    erh_k              NUMERIC(12, 2)
);

COMMENT ON COLUMN fp_jahresstatistik3.id IS 'ID als Sortierkriterium';
COMMENT ON COLUMN fp_jahresstatistik3.jss_jahr IS 'Jahr der Statistik';
COMMENT ON COLUMN fp_jahresstatistik3.foerderbereich IS 'Beschreibung des Förderbereichs';
COMMENT ON COLUMN fp_jahresstatistik3.fb IS 'Nummer des Förderbereichs';
COMMENT ON COLUMN fp_jahresstatistik3.gruppe IS 'Gruppenkennzeichen für Zwischensummen';
COMMENT ON COLUMN fp_jahresstatistik3.bzuwendung_z_plus IS 'Bewilligter Zuschuss im Jahr (positiver Wert)';
COMMENT ON COLUMN fp_jahresstatistik3.bzuwendung_z_minus IS 'Bewilligter Zuschuss im Jahr (negativer Wert)';
COMMENT ON COLUMN fp_jahresstatistik3.bzuwendung_d_plus IS 'Bewilligtes Darlehen im Jahr (positiver Wert)';
COMMENT ON COLUMN fp_jahresstatistik3.bzuwendung_d_minus IS 'Bewilligtes Darlehen im Jahr (negativer Wert)';
COMMENT ON COLUMN fp_jahresstatistik3.bzuwendung_k_plus IS 'Bewilligte Konnexität im Jahr (positiver Wert)';
COMMENT ON COLUMN fp_jahresstatistik3.bzuwendung_k_minus IS 'Bewilligte Konnexität im Jahr (negativer Wert)';
COMMENT ON COLUMN fp_jahresstatistik3.erh_z IS 'Erhaltener Zuschuss im Jahr';
COMMENT ON COLUMN fp_jahresstatistik3.erh_d IS 'Erhaltenes Darlehen im Jahr';
COMMENT ON COLUMN fp_jahresstatistik3.erh_k IS 'Erhaltene Konnexität im Jahr';
COMMENT ON TABLE fp_jahresstatistik3 IS 'Diese Tabelle enthält die generierte Jahresstatistik für Seite II';
--------------------------------------------------------
--  DDL for Table FP_LISTENNAMEN
--------------------------------------------------------

CREATE TABLE fp_listennamen
(
    kurzbez     VARCHAR(3) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN fp_listennamen.kurzbez IS 'Kurzbezeichnung für eine Liste von Stadtbezirken';
COMMENT ON COLUMN fp_listennamen.bezeichnung IS 'Beschreibung zu einem Listennamen';
COMMENT ON TABLE fp_listennamen IS 'Alle Listennamen für die Zusammenstellung mehrerer Stadtbezirke';
--------------------------------------------------------
--  DDL for Table FP_PROJEKTISTKOSTEN
--------------------------------------------------------

CREATE TABLE fp_projektistkosten
(
    pro_projnr VARCHAR(7)     NOT NULL REFERENCES fp_projekte (projnr),
    jahr       NUMERIC(4, 0)  NOT NULL,
    monat      NUMERIC(2, 0)  NOT NULL,
    istkosten  NUMERIC(12, 0) NOT NULL,
    PRIMARY KEY (pro_projnr, jahr, monat)
);

CREATE INDEX ON fp_projektistkosten (pro_projnr);

COMMENT ON COLUMN fp_projektistkosten.pro_projnr IS 'IstKosten bezogen auf ein Förderprojekt';
COMMENT ON COLUMN fp_projektistkosten.jahr IS 'IstKosten bezogen auf ein Jahr';
COMMENT ON COLUMN fp_projektistkosten.monat IS 'IstKosten bezogen auf einen Monat (im Jahr)';
COMMENT ON COLUMN fp_projektistkosten.istkosten IS 'Istkosten in Euro aktueller Gesamtstand';
COMMENT ON TABLE fp_projektistkosten IS 'Enthält die Istkosten der Projekte in Form des monatlich aktuellen Gesamtwerts (dbase:pist, palt*). Diese Tabelle zeigt somit die Entwickung der IST-Kosten im Zeitverlauf jeweils summiert an.';
--------------------------------------------------------
--  DDL for Table FP_PROJEKTTERMINE
--------------------------------------------------------

CREATE TABLE fp_projekttermine
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_projnr   VARCHAR(7)            NOT NULL REFERENCES fp_projekte (projnr),
    termin       DATE                  NOT NULL,
    zustaendig   VARCHAR(60),
    telefon      VARCHAR(30),
    notizen      TEXT,
    ueberwachung BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE INDEX ON fp_projekttermine (pro_projnr);

COMMENT ON COLUMN fp_projekttermine.id IS 'Primary Key als ID';
COMMENT ON COLUMN fp_projekttermine.pro_projnr IS 'Projektbezug eines Termins';
COMMENT ON COLUMN fp_projekttermine.termin IS 'Termin';
COMMENT ON COLUMN fp_projekttermine.zustaendig IS 'Zuständigkeit im Baureferet';
COMMENT ON COLUMN fp_projekttermine.telefon IS 'Telefon des Bauleiters bzw. der Kontaktperson';
COMMENT ON COLUMN fp_projekttermine.notizen IS 'Notizen (Freitext)';
COMMENT ON COLUMN fp_projekttermine.ueberwachung IS 'Kennzeichen für Terminüberwachung';
COMMENT ON TABLE fp_projekttermine IS 'Enthält eine Terminverwaltung bezüglich Projekten (dbase:vnuanf)';
--------------------------------------------------------
--  DDL for Table FP_PROTOKOLL
--------------------------------------------------------

CREATE TABLE fp_protokoll
(
    log_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date          DATE,
    log_module        VARCHAR(100),
    log_gui_user      VARCHAR(30),
    log_message       TEXT,
    log_error_message TEXT
);

COMMENT ON COLUMN fp_protokoll.log_id IS 'Eindeutiger Schluessel für einen Record';
COMMENT ON COLUMN fp_protokoll.log_date IS 'Datum des Ereignisses';
COMMENT ON COLUMN fp_protokoll.log_module IS 'Module des Ereignisses';
COMMENT ON COLUMN fp_protokoll.log_gui_user IS 'Beutzername des Ereignisses';
COMMENT ON COLUMN fp_protokoll.log_message IS 'Log Message';
COMMENT ON COLUMN fp_protokoll.log_error_message IS 'Log Error';
COMMENT ON TABLE fp_protokoll IS 'Diese Tabelle beinhaltet die systemtechnischen Protokolle im Falle von Systemfehlern oder Prozeduren';
--------------------------------------------------------
--  DDL for Table FP_STADTBEZIRKSLISTEN
--------------------------------------------------------

CREATE TABLE fp_stadtbezirkslisten
(
    lna_kurzbez     VARCHAR(3)    NOT NULL REFERENCES fp_listennamen (kurzbez),
    bez_stadtbezirk NUMERIC(2, 0) NOT NULL REFERENCES fp_stadtbezirke (stadtbezirk),
    bezeichnung     VARCHAR(200),
    PRIMARY KEY (lna_kurzbez, bez_stadtbezirk)
);

COMMENT ON COLUMN fp_stadtbezirkslisten.lna_kurzbez IS 'Kurzbezeichnung der Stadtbezirksliste';
COMMENT ON COLUMN fp_stadtbezirkslisten.bez_stadtbezirk IS 'Nummer des Stadtbezirks';
COMMENT ON COLUMN fp_stadtbezirkslisten.bezeichnung IS 'Notizen zu diesem Eintrag';
COMMENT ON TABLE fp_stadtbezirkslisten IS 'Zuordnung von Stadtbezirken zu einer Stadtbezirksliste';
--------------------------------------------------------
--  DDL for Table FP_TRAEGER
--------------------------------------------------------

CREATE TABLE fp_traeger
(
    kurzform    NUMERIC(1, 0) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN fp_traeger.kurzform IS 'Kurzform für den Träger des Städtebauförderprogramms';
COMMENT ON COLUMN fp_traeger.bezeichnung IS 'Beschreibung des Trägers des Städebauförderprogramms';
COMMENT ON TABLE fp_traeger IS 'Enthält Träger der Städtebauförderprogramme';
--------------------------------------------------------
--  DDL for Table FP_STAEDTEBAUFOERDERUNGEN
--------------------------------------------------------

CREATE TABLE fp_staedtebaufoerderungen
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bdat         DATE,
    bnr          NUMERIC(4, 0),
    bjahr        NUMERIC(4, 0),
    betrag       NUMERIC(10, 0),
    soz          BOOLEAN DEFAULT FALSE NOT NULL,
    azbank       VARCHAR(40),
    antrnr       NUMERIC(3, 0),
    antrjahr     NUMERIC(4, 0),
    azstk        VARCHAR(6),
    ausbet       NUMERIC(10, 0),
    erhdat       DATE,
    tra_kurzform NUMERIC(1, 0) REFERENCES fp_traeger (kurzform),
    hst          VARCHAR(15),
    hulnr        VARCHAR(5),
    huljahr      NUMERIC(4, 0),
    notizen      TEXT,
    projektname  VARCHAR(60),
    restlos      DATE,
    zahlanz      DATE,
    schuldurk    BOOLEAN DEFAULT FALSE NOT NULL,
    alt_lfdnr    NUMERIC(10, 0)
);

COMMENT ON COLUMN fp_staedtebaufoerderungen.id IS 'Eindeutiger Schluessel für einen Datensatz';
COMMENT ON COLUMN fp_staedtebaufoerderungen.bdat IS 'Datum der Bewilligung';
COMMENT ON COLUMN fp_staedtebaufoerderungen.bnr IS 'Bescheidnummer';
COMMENT ON COLUMN fp_staedtebaufoerderungen.bjahr IS 'Jahr der Bewilligung';
COMMENT ON COLUMN fp_staedtebaufoerderungen.betrag IS 'Bewilligter Betrag';
COMMENT ON COLUMN fp_staedtebaufoerderungen.soz IS 'Kennzeichen Soz Stadt';
COMMENT ON COLUMN fp_staedtebaufoerderungen.azbank IS 'Aktenzeichen der Bank';
COMMENT ON COLUMN fp_staedtebaufoerderungen.antrnr IS 'Antragsnummer';
COMMENT ON COLUMN fp_staedtebaufoerderungen.antrjahr IS 'Antragsjahr';
COMMENT ON COLUMN fp_staedtebaufoerderungen.azstk IS 'Aktenzeichen der Stadtkämmerei';
COMMENT ON COLUMN fp_staedtebaufoerderungen.ausbet IS 'Ausbezahlter Betrag';
COMMENT ON COLUMN fp_staedtebaufoerderungen.erhdat IS 'Datum des Geldeingangs';
COMMENT ON COLUMN fp_staedtebaufoerderungen.tra_kurzform IS 'Träger des Städtebauförderprogramms';
COMMENT ON COLUMN fp_staedtebaufoerderungen.hst IS 'Haushaltsstelle der Stadt als Freitext';
COMMENT ON COLUMN fp_staedtebaufoerderungen.hulnr IS 'Hül Nummer der Stadt';
COMMENT ON COLUMN fp_staedtebaufoerderungen.huljahr IS 'Hül Jahr';
COMMENT ON COLUMN fp_staedtebaufoerderungen.notizen IS 'Notizen';
COMMENT ON COLUMN fp_staedtebaufoerderungen.projektname IS 'Name des Projekts';
COMMENT ON COLUMN fp_staedtebaufoerderungen.restlos IS 'Datum der Restlosanzeige an Dienststelle';
COMMENT ON COLUMN fp_staedtebaufoerderungen.zahlanz IS 'Zahlungsanzeige erhalten am';
COMMENT ON COLUMN fp_staedtebaufoerderungen.schuldurk IS 'Schuldurkunde ausgestellt';
COMMENT ON COLUMN fp_staedtebaufoerderungen.alt_lfdnr IS 'Lfdnr zur Altdatenübernahme der Memos';
COMMENT ON TABLE fp_staedtebaufoerderungen IS 'Aufstellung aller Programme zur Städtebauförderung als eingeständige Anwendung (dbase:stadt)';