--------------------------------------------------------
--  stichwortbereiche
--------------------------------------------------------

CREATE TABLE stichwortbereiche
(
    bereich     VARCHAR(30) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN stichwortbereiche.bereich IS 'Definierter Bereich für die Stichwortvergabe';
COMMENT ON COLUMN stichwortbereiche.bezeichnung IS 'Bezeichnung dieses Stichwortbereichs';
COMMENT ON TABLE stichwortbereiche IS 'Verzeichnis aller Stichwortbereiche (Nutzung in Ablageindexe)';
--------------------------------------------------------
--  ablageindexe
--------------------------------------------------------

CREATE TABLE ablageindexe
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stb_bereich VARCHAR(30) NOT NULL REFERENCES stichwortbereiche (bereich),
    nr          NUMERIC(4),
    wort        VARCHAR(80),
    stichworte  VARCHAR(400)
);

COMMENT ON COLUMN ablageindexe.id IS 'Primary Key (Sequence)';
COMMENT ON COLUMN ablageindexe.stb_bereich IS 'Bereich und Bezeichnung des Ablagedeckblattes';
COMMENT ON COLUMN ablageindexe.nr IS 'Lfd. Nummer innerhalb des Deckblattes';
COMMENT ON COLUMN ablageindexe.wort IS 'Thema des Schriftgutes';
COMMENT ON COLUMN ablageindexe.stichworte IS 'Stichwort (Index) nach dem gesucht werden kann';
COMMENT ON TABLE ablageindexe IS 'Suchindex zum Auffinden von Ablagen (dbase:hinh)';
--------------------------------------------------------
--  referate
--------------------------------------------------------

CREATE TABLE referate
(
    refnr       NUMERIC(2) PRIMARY KEY,
    bezeichnung VARCHAR(200)
);

COMMENT ON COLUMN referate.refnr IS 'Nummer des Referats';
COMMENT ON COLUMN referate.bezeichnung IS 'Beschreibung des Referats';
COMMENT ON TABLE referate IS 'Aufstellung aller Referate  (dbase:referate)';
--------------------------------------------------------
--  foerderbereiche
--------------------------------------------------------

CREATE TABLE foerderbereiche
(
    fb              NUMERIC(2) PRIMARY KEY,
    bezeichnung     VARCHAR(200)          NOT NULL,
    finanzausgleich BOOLEAN DEFAULT FALSE NOT NULL,
    jahresstatistik BOOLEAN DEFAULT FALSE NOT NULL,
    kindergarten    BOOLEAN DEFAULT FALSE NOT NULL,
    nicht_relevant  BOOLEAN DEFAULT FALSE NOT NULL
);

COMMENT ON COLUMN foerderbereiche.fb IS 'Abkürzung des Förderbereichs';
COMMENT ON COLUMN foerderbereiche.bezeichnung IS 'Bezeichnung des Förderbereichs';
COMMENT ON COLUMN foerderbereiche.finanzausgleich IS 'Soll der Förderbereich in der FAG-Statistik verwendet werden';
COMMENT ON COLUMN foerderbereiche.jahresstatistik IS 'Soll der Förderbereich in der Jahresstatistik verwendet werden';
COMMENT ON COLUMN foerderbereiche.kindergarten IS 'Ist der Förderbereich vom Typ Kindergarten. Wird verwendet in Jahresstatistik.';
COMMENT ON COLUMN foerderbereiche.nicht_relevant IS 'Der Förderbereich kann als nicht relevant gekennzeichnet werden. Damit Aussteuerung in manchen Berichten';
COMMENT ON TABLE foerderbereiche IS 'Austellung aller Förderbereiche (dbase:fb)';
--------------------------------------------------------
--  kurzbezeichnungen
--------------------------------------------------------

CREATE TABLE kurzbezeichnungen
(
    kurzbez     VARCHAR(8) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN kurzbezeichnungen.kurzbez IS 'Kurzbezeichnung für eine Projekt';
COMMENT ON COLUMN kurzbezeichnungen.bezeichnung IS 'Beschreibung zu einer Kurzbezeichnung';
COMMENT ON TABLE kurzbezeichnungen IS 'Alle Kurzbezeichnungen zur Klassiifzierung von Projekten  (dbase:kurzbez)';
--------------------------------------------------------
--  hauptabschnitte
--------------------------------------------------------

CREATE TABLE hauptabschnitte
(
    ha          VARCHAR(2) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN hauptabschnitte.ha IS 'Hauptabschnitt';
COMMENT ON COLUMN hauptabschnitte.bezeichnung IS 'Bezeichnung des Hauptabschnitts';
COMMENT ON TABLE hauptabschnitte IS 'Hauptabschnitte zur Klassifizierung der Unterabschnitte (dbase: keine Datei vorhanden)';
--------------------------------------------------------
--  unterabschnitte
--------------------------------------------------------

CREATE TABLE unterabschnitte
(
    ua          VARCHAR(2) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL,
    has_ha      VARCHAR(2)   NOT NULL REFERENCES hauptabschnitte (ha)
);

COMMENT ON COLUMN unterabschnitte.ua IS 'Nummer des Unterabschnitts';
COMMENT ON COLUMN unterabschnitte.bezeichnung IS 'Bezeichnung des Unterabschnitts';
COMMENT ON COLUMN unterabschnitte.has_ha IS 'Nummer des Hauptabschnitt des UAs (FK)';
COMMENT ON TABLE unterabschnitte IS 'Unterabschnitte als Teil1 der Projektnummer (dbase: keine Datei vorhanden)';
--------------------------------------------------------
--  bauleitungen
--------------------------------------------------------

CREATE TABLE bauleitungen
(
    bauleitung  VARCHAR(1) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN bauleitungen.bauleitung IS 'Abkürzung der Bauleitung wie H,1,S';
COMMENT ON COLUMN bauleitungen.bezeichnung IS 'Beschreibung der Bauleitung';
COMMENT ON TABLE bauleitungen IS 'Aufstellung aller Bauleitungen als Stammdaten';
--------------------------------------------------------
--  stadtbezirke
--------------------------------------------------------

CREATE TABLE stadtbezirke
(
    stadtbezirk NUMERIC(2) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN stadtbezirke.stadtbezirk IS 'Nummer des Stadtbezirks';
COMMENT ON COLUMN stadtbezirke.bezeichnung IS 'Beschreibung des Bezirks';
COMMENT ON TABLE stadtbezirke IS 'Aufstellung aller Stadtbezirke';
--------------------------------------------------------
--  krankenhaeuser
--------------------------------------------------------

CREATE TABLE krankenhaeuser
(
    krhname     VARCHAR(1) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN krankenhaeuser.krhname IS 'Abkürzung des Krankenhauses wie B, R';
COMMENT ON COLUMN krankenhaeuser.bezeichnung IS 'Beschreibung des Krankenhauses';
COMMENT ON TABLE krankenhaeuser IS 'Aufstellung aller Krankenhäuser als Stammdaten';
--------------------------------------------------------
--  bauprogramme
--------------------------------------------------------

CREATE TABLE bauprogramme
(
    bauprogramm NUMERIC(2) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN bauprogramme.bauprogramm IS 'Nummer des Bauprogramms';
COMMENT ON COLUMN bauprogramme.bezeichnung IS 'Beschreibung des Bauprogramms';
COMMENT ON TABLE bauprogramme IS 'Aufstellung aller Bauprogramme';
--------------------------------------------------------
--  siedlungsgebiete
--------------------------------------------------------

CREATE TABLE siedlungsgebiete
(
    siedlungsgebiet NUMERIC(2) PRIMARY KEY,
    bezeichnung     VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN siedlungsgebiete.siedlungsgebiet IS 'Nummer des Siedlungsgebiets';
COMMENT ON COLUMN siedlungsgebiete.bezeichnung IS 'Beschreibung des Siedlungsgebiets';
COMMENT ON TABLE siedlungsgebiete IS 'Aufstellung aller Siedlungsgebiete';
--------------------------------------------------------
--  projekte
--------------------------------------------------------
CREATE TABLE projekte
(
    projnr              VARCHAR(7) PRIMARY KEY,
    fob_fb              NUMERIC(2)                   NOT NULL REFERENCES foerderbereiche (fb),
    kur_kurzbez         VARCHAR(8)                   NOT NULL REFERENCES kurzbezeichnungen (kurzbez),
    uas_ua              VARCHAR(2)                   NOT NULL REFERENCES unterabschnitte (ua),
    jahr                VARCHAR(2)                   NOT NULL,
    lfdnr1              VARCHAR(1)                   NOT NULL,
    lfdnr2              VARCHAR(2)                   NOT NULL,
    pname               VARCHAR(100),
    pstrasse            VARCHAR(100),
    kauf                BOOLEAN DEFAULT FALSE        NOT NULL,
    projart             VARCHAR(50),
    refinanzierbar      BOOLEAN DEFAULT TRUE         NOT NULL,
    ble_bauleitung      VARCHAR(1) REFERENCES bauleitungen (bauleitung),
    bauleitungkontakt   VARCHAR(30),
    bez_stadtbezirk     NUMERIC(2) REFERENCES stadtbezirke (stadtbezirk),
    krn_krhname         VARCHAR(1) REFERENCES krankenhaeuser (krhname),
    krhzweck            projekte_krhzweck,
    krisofp             projekte_krisofp,
    kripplatz           NUMERIC(10),
    kigaplatz           NUMERIC(10),
    hortplatz           NUMERIC(10),
    vndat               DATE,
    vnkosten            NUMERIC(12, 2),
    vnzwfkosten         NUMERIC(12, 2),
    vnpruefdat          DATE,
    vnrueck_z           NUMERIC(12, 2),
    vnnachfoerderung    NUMERIC(12, 2),
    vnpruefzwf          NUMERIC(12, 2),
    vnschlusszwf        NUMERIC(12, 2),
    vnschlussbew        DATE,
    sap                 BOOLEAN DEFAULT FALSE        NOT NULL,
    sapstatauf          BOOLEAN DEFAULT FALSE        NOT NULL,
    sapmatnr            NUMERIC(8),
    sapwertnr           NUMERIC(8),
    sapjahrwert         DATE,
    sapanlagennr        NUMERIC(8),
    zinsen              NUMERIC(10),
    zinsdatum           DATE,
    fipo                VARCHAR(15),
    buchungskreis       VARCHAR(4),
    sachkonto           VARCHAR(6),
    fipo_k              VARCHAR(15),
    buchungskreis_k     VARCHAR(4),
    sachkonto_k         VARCHAR(6),
    psbaubuch           VARCHAR(2),
    psbauref            projekte_psbauref,
    psbaunr             VARCHAR(6),
    notizen             TEXT,
    altdaten            BOOLEAN DEFAULT FALSE        NOT NULL,
    anlagedatum         DATE    DEFAULT CURRENT_DATE NOT NULL,
    anlagevon           VARCHAR(30)                  NOT NULL,
    aenderungsdatum     DATE,
    aenderungvon        VARCHAR(30),
    vngesamtzuwendung   NUMERIC(12, 2),
    sapinnenauftrag     VARCHAR(12),
    bpg_bauprogramm     NUMERIC(2) REFERENCES bauprogramme (bauprogramm),
    sgt_siedlungsgebiet NUMERIC(2) REFERENCES siedlungsgebiete (siedlungsgebiet),
    bauende             DATE,
    baubeendet          projekte_baubeendet,
    bauvergabe1         DATE,
    baubeginn           DATE,
    baumitteilung       DATE,
    kreditnummer        NUMERIC(8),
    stadtanleihe        VARCHAR(50),
    anleihenennwert     NUMERIC(9),
    anleihejahrvon      NUMERIC(4),
    anleihejahrbis      NUMERIC(4)
);

CREATE INDEX ON projekte (aenderungsdatum);
CREATE INDEX ON projekte (bez_stadtbezirk);
CREATE INDEX ON projekte (ble_bauleitung);
CREATE INDEX ON projekte (bpg_bauprogramm);
CREATE INDEX ON projekte (fob_fb);
CREATE INDEX ON projekte (krn_krhname);
CREATE INDEX ON projekte (kur_kurzbez);
CREATE INDEX ON projekte (sgt_siedlungsgebiet);
CREATE INDEX ON projekte (uas_ua);

COMMENT ON COLUMN projekte.projnr IS 'Primary Key Projektnummer zusammengesetzt';
COMMENT ON COLUMN projekte.fob_fb IS 'Förderbereich Kurzform';
COMMENT ON COLUMN projekte.kur_kurzbez IS 'Kurzbezeichnung zur Klassifizierung eines Projekts';
COMMENT ON COLUMN projekte.uas_ua IS 'Unterabschnitt als Teil der Projektnummer (Stelle 1-2)';
COMMENT ON COLUMN projekte.jahr IS 'Jahreszahl zweistellig als Teil der Projektnummer (Stelle 3-4)';
COMMENT ON COLUMN projekte.lfdnr1 IS 'Laufende Nummer einstellig als Teil der Projektnummer (Stelle 5)';
COMMENT ON COLUMN projekte.lfdnr2 IS 'Laufende Nummer zweistellig als Teil der Projektnummer (Stelle 6-7)';
COMMENT ON COLUMN projekte.pname IS 'Name des Projekts (altes Verfahren: beginnend mit der Straße)';
COMMENT ON COLUMN projekte.pstrasse IS 'Straße des Projekts allein';
COMMENT ON COLUMN projekte.kauf IS 'Liegt ein Ankauf oder Teilerwerb vor';
COMMENT ON COLUMN projekte.projart IS 'Beschreibung des Projekts etwa Umbau, Neubau (Freitext)';
COMMENT ON COLUMN projekte.refinanzierbar IS 'Ist dieses Förderprojekt refinanzierbar';
COMMENT ON COLUMN projekte.ble_bauleitung IS 'Zuständige Abteilung im Baureferat (FK)';
COMMENT ON COLUMN projekte.bauleitungkontakt IS 'Baustand: Name des Projektleiters sowie Telefon';
COMMENT ON COLUMN projekte.bez_stadtbezirk IS 'Nummer des Stadtbezirks (FK)';
COMMENT ON COLUMN projekte.krn_krhname IS 'Kurzbezeichnung Krankenhausname (FK)';
COMMENT ON COLUMN projekte.krhzweck IS 'Förderung nach Jahreskrankenhausbauprogramm';
COMMENT ON COLUMN projekte.krisofp IS 'Art des Krippensonderförderprogramms';
COMMENT ON COLUMN projekte.kripplatz IS 'Anzahl der Krippenplätze';
COMMENT ON COLUMN projekte.kigaplatz IS 'Anzahl der Kindergartenplätze';
COMMENT ON COLUMN projekte.hortplatz IS 'Anzahl der Hortplätze';
COMMENT ON COLUMN projekte.vndat IS 'Datum des abgeschlossenen Verwendungsnachweises.';
COMMENT ON COLUMN projekte.vnkosten IS 'Endkosten lt. Verwendungsnachweis';
COMMENT ON COLUMN projekte.vnzwfkosten IS 'Zuwendungsfähige Gesamtkosten lt. Verwendungsnachweis';
COMMENT ON COLUMN projekte.vnpruefdat IS 'Datum der Prüfung des Verwendungsnachweises lt. Zuwendungsgeber';
COMMENT ON COLUMN projekte.vnrueck_z IS 'Höhe des zurückgeforderten Zuschussbetrags  lt. Verwendungsnachweis';
COMMENT ON COLUMN projekte.vnnachfoerderung IS 'Höhe der Nachförderung (Zuschuss)  lt. Verwendungsnachweis';
COMMENT ON COLUMN projekte.vnpruefzwf IS 'Höhe der geprüften zuwendungsfähigen Kosten  lt. Verwendungsnachweis';
COMMENT ON COLUMN projekte.vnschlusszwf IS 'Höhe der endgültigen zuwendungsfähigen Kosten  lt. Verwendungsnachweis';
COMMENT ON COLUMN projekte.vnschlussbew IS 'Datum des letzten Bewilligungsbescheids (Schlussbescheid)  lt. Verwendungsnachweis';
COMMENT ON COLUMN projekte.sap IS 'Wird dieses Projekt in SAP geführt';
COMMENT ON COLUMN projekte.sapstatauf IS 'Statistischer Innenauftrag';
COMMENT ON COLUMN projekte.sapmatnr IS 'SAP Materialnummer';
COMMENT ON COLUMN projekte.sapwertnr IS 'SAP Wertkontraktnummer';
COMMENT ON COLUMN projekte.sapjahrwert IS 'Datum in SAP (Jahr Wertkontrakt)';
COMMENT ON COLUMN projekte.sapanlagennr IS 'SAP Anlagennummer';
COMMENT ON COLUMN projekte.zinsen IS 'Höhe der Zinszahlungen';
COMMENT ON COLUMN projekte.zinsdatum IS 'Datum der Zinszahlungen';
COMMENT ON COLUMN projekte.fipo IS 'Finanzposition im Haushalt (Haushaltsstelle) für Zuwendungen';
COMMENT ON COLUMN projekte.buchungskreis IS 'SAP Buchungskreis für Zuwendungen';
COMMENT ON COLUMN projekte.sachkonto IS 'SAP Sachkonto für Zuwendungen';
COMMENT ON COLUMN projekte.fipo_k IS 'Finanzposition im Haushalt (Haushaltsstelle) für Erstattungen';
COMMENT ON COLUMN projekte.buchungskreis_k IS 'SAP Buchungskreis für Erstattungen';
COMMENT ON COLUMN projekte.sachkonto_k IS 'SAP Sachkonto für Erstattungen';
COMMENT ON COLUMN projekte.psbaubuch IS 'Projektstruktur Baubuchnummer Teil1';
COMMENT ON COLUMN projekte.psbauref IS 'Projektstruktur Baubuchnummer Teil2';
COMMENT ON COLUMN projekte.psbaunr IS 'Projektstruktur Baubuchnummer Teil3';
COMMENT ON COLUMN projekte.notizen IS 'Notizen zum Projekt, Baustand und VN (Freitext)';
COMMENT ON COLUMN projekte.altdaten IS 'Kennzeichen ob dieses Projekt aus der Altdatenübernahme stammt 0=nein, 1=ja';
COMMENT ON COLUMN projekte.anlagedatum IS 'Dieser Satz wurde angelegt am';
COMMENT ON COLUMN projekte.anlagevon IS 'Dieser Satz wurde angelegt von diesem Benutzer';
COMMENT ON COLUMN projekte.aenderungsdatum IS 'Dieser Satz wurde zuletzt geändert am';
COMMENT ON COLUMN projekte.aenderungvon IS 'Dieser Satz wurde zuletzt geändert von diesem Benutzer';
COMMENT ON COLUMN projekte.vngesamtzuwendung IS 'Im Schlussbescheid festgesetzte Gesamtzuwendung seitens der Fördermittelgebers';
COMMENT ON COLUMN projekte.sapinnenauftrag IS 'SAP Innenauftrag';
COMMENT ON COLUMN projekte.bpg_bauprogramm IS 'Nummer des zugehörigen Bauprogramms (FK)';
COMMENT ON COLUMN projekte.sgt_siedlungsgebiet IS 'Nummer des zugehörigen Siedlungsgebietes (FK)';
COMMENT ON COLUMN projekte.bauende IS 'Datum des voraussichtlichen oder endgültigen Bauendes';
COMMENT ON COLUMN projekte.baubeendet IS 'Status zum Datum des Bauendes';
COMMENT ON COLUMN projekte.bauvergabe1 IS 'Wann erfolgte die erste Vergabe zum Bau';
COMMENT ON COLUMN projekte.baubeginn IS 'Wann erfolgte der offizielle Baubeginn';
COMMENT ON COLUMN projekte.baumitteilung IS 'Wann erfolgte die letzte Mitteilung zum Bau';
COMMENT ON COLUMN projekte.kreditnummer IS 'Kreditnummer von der Kämmerei vergeben';
COMMENT ON COLUMN projekte.stadtanleihe IS 'Falls Stadtanleihe dann Beschreibung oder Titel der Stadtanleihe';
COMMENT ON COLUMN projekte.anleihenennwert IS 'Höhe der Anleihe (Nominalwert)';
COMMENT ON COLUMN projekte.anleihejahrvon IS 'Laufzeit der Anleihe (Jahr von)';
COMMENT ON COLUMN projekte.anleihejahrbis IS 'Laufzeit der Anleihe (Jahr bis)';
COMMENT ON TABLE projekte IS 'Alle Projekte der Fördermittelverwaltung (dbase:projekte,kindbetr,vn)';
--------------------------------------------------------
--  antraege
--------------------------------------------------------

CREATE TABLE antraege
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_projnr      VARCHAR(7)                   NOT NULL REFERENCES projekte (projnr),
    antragsdatum    DATE,
    antragstyp      antraege_antragstyp          NOT NULL,
    geskosten       NUMERIC(10)                  NOT NULL,
    zwfkosten       NUMERIC(10)                  NOT NULL,
    vorzbeg         BOOLEAN DEFAULT FALSE        NOT NULL,
    vbdatum         DATE,
    unbeddat        DATE,
    unbedja         DATE,
    unbedbis        DATE,
    a_su_z          NUMERIC(10)                  NOT NULL,
    a_su_d          NUMERIC(10)                  NOT NULL,
    a_su_k          NUMERIC(10)                  NOT NULL,
    b_vor_su_z      NUMERIC(10)                  NOT NULL,
    b_vor_su_d      NUMERIC(10)                  NOT NULL,
    b_vor_su_k      NUMERIC(10)                  NOT NULL,
    notizen         TEXT,
    anlagedatum     DATE    DEFAULT CURRENT_DATE NOT NULL,
    anlagevon       VARCHAR(30)                  NOT NULL,
    aenderungsdatum DATE,
    aenderungvon    VARCHAR(30)
);

CREATE INDEX ON antraege (pro_projnr);

COMMENT ON COLUMN antraege.id IS 'Primärschlüssel eines Fördermittelantrags';
COMMENT ON COLUMN antraege.pro_projnr IS 'Dieser Antrag bezieht sich auf dieses Projekt';
COMMENT ON COLUMN antraege.antragsdatum IS 'Datum des Förderantrags';
COMMENT ON COLUMN antraege.antragstyp IS 'Typ des Förderantrags';
COMMENT ON COLUMN antraege.geskosten IS 'Beantragte Gesamtkosten des Projekts bei diesem Antrag (besonders beim Erstantrag)';
COMMENT ON COLUMN antraege.zwfkosten IS 'Beantragte zuwendungsfähige Gesamtkosten bei diesem Antrag';
COMMENT ON COLUMN antraege.vorzbeg IS 'Wurde Antrag auf vorzeitigen Baubeginn gestellt';
COMMENT ON COLUMN antraege.vbdatum IS 'Datum eines vorzeitigen Baubeginns';
COMMENT ON COLUMN antraege.unbeddat IS 'Datum des Antrags auf Unbedenklichkeit';
COMMENT ON COLUMN antraege.unbedja IS 'Datum der erteilten Unbedenklichkeitsbescheinigung';
COMMENT ON COLUMN antraege.unbedbis IS 'Die erteilte Unbedenklichkeitsbescheinigung ist gültig bis zu diesem Datum';
COMMENT ON COLUMN antraege.a_su_z IS 'Höhe des beantragten Zuschusses (nur Anteil für ein Jahr)';
COMMENT ON COLUMN antraege.a_su_d IS 'Höhe des beantragten Darlehens (nur Anteil für ein Jahr)';
COMMENT ON COLUMN antraege.a_su_k IS 'Höhe der beantragten Kostenerstattung (Konnexität, nur Anteil für ein Jahr)';
COMMENT ON COLUMN antraege.b_vor_su_z IS 'voraussichtlich bewilligte Gesamtzuwendung';
COMMENT ON COLUMN antraege.b_vor_su_d IS 'voraussichtlich bewilligtes Gesamtdarlehen';
COMMENT ON COLUMN antraege.b_vor_su_k IS ' voraussichtlich bewilligte Kostenerstattung';
COMMENT ON COLUMN antraege.notizen IS 'Notizen zu einem Antrag als Freitext';
COMMENT ON COLUMN antraege.anlagedatum IS 'Dieser Satz wurde angelegt am';
COMMENT ON COLUMN antraege.anlagevon IS 'Dieser Satz wurde angelegt von diesem Benutzer';
COMMENT ON COLUMN antraege.aenderungsdatum IS 'Dieser Satz wurde zuletzt geändert am';
COMMENT ON COLUMN antraege.aenderungvon IS 'Dieser Satz wurde zuletzt geändert von diesem Benutzer';
COMMENT ON TABLE antraege IS 'Enthält alle Förderanträge zu Projekten (dbase:erstantr)';
--------------------------------------------------------
--  bewilligungen
--------------------------------------------------------

CREATE TABLE bewilligungen
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_projnr      VARCHAR(7)                NOT NULL REFERENCES projekte (projnr),
    ant_id          BIGINT REFERENCES antraege (id),
    bdatum          DATE,
    afsatz          NUMERIC(8, 2)             NOT NULL,
    bfsatz          NUMERIC(8, 2)             NOT NULL,
    bzwfkosten      NUMERIC(10)               NOT NULL,
    bzuwendung_z    NUMERIC(10),
    bzuwendung_d    NUMERIC(10),
    bzuwendung_k    NUMERIC(10),
    bzuwart         bewilligungen_bzuwart,
    baktenzeichen   VARCHAR(20),
    geszuwendungen  NUMERIC(10)               NOT NULL,
    geskonnex       NUMERIC(10)               NOT NULL,
    krw             bewilligungen_krw,
    notizen         TEXT,
    anlagedatum     DATE DEFAULT CURRENT_DATE NOT NULL,
    anlagevon       VARCHAR(30)               NOT NULL,
    aenderungsdatum DATE,
    aenderungvon    VARCHAR(30)
);

CREATE INDEX ON bewilligungen (ant_id);
CREATE INDEX ON bewilligungen (pro_projnr);

COMMENT ON COLUMN bewilligungen.id IS 'Primärschlüssel einer Bewilligung';
COMMENT ON COLUMN bewilligungen.pro_projnr IS 'Diese Bewilligung bezieht sich auf dieses Projekt';
COMMENT ON COLUMN bewilligungen.ant_id IS 'Diese Bewilligung bezieht sich auf einen Antrag';
COMMENT ON COLUMN bewilligungen.bdatum IS 'Datum der Bewilligung';
COMMENT ON COLUMN bewilligungen.afsatz IS 'Beantrager Fördersatz';
COMMENT ON COLUMN bewilligungen.bfsatz IS 'Bewilligter Fördersatz';
COMMENT ON COLUMN bewilligungen.bzwfkosten IS 'bewilligte zuwendungsfähige Kosten Gesamtbetrag';
COMMENT ON COLUMN bewilligungen.bzuwendung_z IS 'Bewilligte Zuwendung auf Jahresbasis als Zuschuss';
COMMENT ON COLUMN bewilligungen.bzuwendung_d IS 'Bewilligte Zuwendung auf Jahresbasis als Darlehen';
COMMENT ON COLUMN bewilligungen.bzuwendung_k IS 'Bewilligte Zuwendung auf Jahresbasis als Kostenerstattung';
COMMENT ON COLUMN bewilligungen.bzuwart IS 'Bewilligte Zuwendungsart';
COMMENT ON COLUMN bewilligungen.baktenzeichen IS 'Aktenzeichen des Bewilligers';
COMMENT ON COLUMN bewilligungen.geszuwendungen IS 'Höhe der zu erwartenden Gesamtzuwendungen für das Förderprojekt zum Zeitpunkt dieser Bewilligung';
COMMENT ON COLUMN bewilligungen.geskonnex IS 'Höhe der zu erwartenden Gesamtkonnexitätszahlungen für das Förderprojekt zum Zeitpunkt dieser Bewilligung';
COMMENT ON COLUMN bewilligungen.krw IS 'Typ des Kostenrichtwerts';
COMMENT ON COLUMN bewilligungen.notizen IS 'Notizen zu einer Bewilligung als Freitext';
COMMENT ON COLUMN bewilligungen.anlagedatum IS 'Dieser Satz wurde angelegt am';
COMMENT ON COLUMN bewilligungen.anlagevon IS 'Dieser Satz wurde angelegt von diesem Benutzer';
COMMENT ON COLUMN bewilligungen.aenderungsdatum IS 'Dieser Satz wurde zuletzt geändert am';
COMMENT ON COLUMN bewilligungen.aenderungvon IS 'Dieser Satz wurde zuletzt geändert von diesem Benutzer';
COMMENT ON TABLE bewilligungen IS 'Enthält alle Bewilligungen zu Förderanträgen. (dbase:bewill)';
--------------------------------------------------------
--  abrufe
--------------------------------------------------------

CREATE TABLE abrufe
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_projnr         VARCHAR(7)                NOT NULL REFERENCES projekte (projnr),
    bwi_id             BIGINT REFERENCES bewilligungen (id),
    vnabr              abrufe_vnabr,
    abruf_z            NUMERIC(10)               NOT NULL,
    abruf_d            NUMERIC(10)               NOT NULL,
    abruf_k            NUMERIC(10)               NOT NULL,
    abruf_datum        DATE,
    erh_z              NUMERIC(10)               NOT NULL,
    erh_d              NUMERIC(10)               NOT NULL,
    erh_k              NUMERIC(10)               NOT NULL,
    erh_datum          DATE,
    ref_refnr          NUMERIC(2) REFERENCES referate (refnr),
    sapabrufauftragsnr NUMERIC(8),
    sapfakturanr       NUMERIC(10),
    fipo               VARCHAR(15),
    buchungskreis      VARCHAR(4),
    sachkonto          VARCHAR(6),
    fipo_k             VARCHAR(15),
    buchungskreis_k    VARCHAR(4),
    sachkonto_k        VARCHAR(6),
    notizen            TEXT,
    anlagedatum        DATE DEFAULT CURRENT_DATE NOT NULL,
    anlagevon          VARCHAR(30)               NOT NULL,
    aenderungsdatum    DATE,
    aenderungvon       VARCHAR(30)
);

CREATE INDEX ON abrufe (bwi_id);
CREATE INDEX ON abrufe (pro_projnr);
CREATE INDEX ON abrufe (ref_refnr);

COMMENT ON COLUMN abrufe.id IS 'Primärschlüssel eines Abrufs';
COMMENT ON COLUMN abrufe.pro_projnr IS 'Dieser Abruf bezieht sich auf dieses Projekt';
COMMENT ON COLUMN abrufe.bwi_id IS 'Dieser Abruf bezieht sich auf eine Bewilligung';
COMMENT ON COLUMN abrufe.vnabr IS 'Ist der Abruf mit dem Verwendungsnachweis erfolgt';
COMMENT ON COLUMN abrufe.abruf_z IS 'Höhe der abgerufenen Zuwendung';
COMMENT ON COLUMN abrufe.abruf_d IS 'Höhe des abgerufenen Darlehens';
COMMENT ON COLUMN abrufe.abruf_k IS 'Höhe des abgerufenen Konnexitätsbetrags (Kostenerstattung)';
COMMENT ON COLUMN abrufe.abruf_datum IS 'Datum an dem der Abruf erfolgte';
COMMENT ON COLUMN abrufe.erh_z IS 'Höhe der erhaltenen Zuwendung';
COMMENT ON COLUMN abrufe.erh_d IS 'Höhe des erhaltenen Darlehens';
COMMENT ON COLUMN abrufe.erh_k IS 'Höhe der erhaltenen Konnexität (Kostenerstattung)';
COMMENT ON COLUMN abrufe.erh_datum IS 'Datum des Geldeingangs';
COMMENT ON COLUMN abrufe.ref_refnr IS 'Nummer des betroffenen Referats für diesen Abruf';
COMMENT ON COLUMN abrufe.sapabrufauftragsnr IS 'SAP Auftragsnummer für diesen Abruf';
COMMENT ON COLUMN abrufe.sapfakturanr IS 'SAP Fakturanummer für diesen Abruf';
COMMENT ON COLUMN abrufe.fipo IS 'Haushaltsstelle (FIPO) für Zuwendungen für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN abrufe.buchungskreis IS 'SAP Buchungskreis für Zuwendungen  für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN abrufe.sachkonto IS 'SAP Sachkonto für Zuwendungen  für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN abrufe.fipo_k IS 'Haushaltsstelle (FIPO) für Kostenerstattungen  für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN abrufe.buchungskreis_k IS 'SAP Buchungskreis für Kostenerstattungen  für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN abrufe.sachkonto_k IS 'SAP Sachkonto für Kostenerstattungen  für diesen Abruf (default aus Projekt)';
COMMENT ON COLUMN abrufe.notizen IS 'Notizen zum Abruf als Freitext';
COMMENT ON COLUMN abrufe.anlagedatum IS 'Dieser Satz wurde angelegt am';
COMMENT ON COLUMN abrufe.anlagevon IS 'Dieser Satz wurde angelegt von diesem Benutzer';
COMMENT ON COLUMN abrufe.aenderungsdatum IS 'Dieser Satz wurde zuletzt geändert am';
COMMENT ON COLUMN abrufe.aenderungvon IS 'Dieser Satz wurde zuletzt geändert von diesem Benutzer';
COMMENT ON TABLE abrufe IS 'Enthält die Abrufe zu den Bewilligungen eines Projekts (dbase:abrufe)';
--------------------------------------------------------
--  archiv
--------------------------------------------------------

CREATE TABLE archiv
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_projnr         VARCHAR(7) REFERENCES projekte (projnr),
    speicherdatum      DATE,
    speicherakt        BOOLEAN DEFAULT FALSE NOT NULL,
    speicherrechnungen BOOLEAN DEFAULT FALSE NOT NULL,
    mikrodatplan       DATE,
    mikrodat           DATE,
    notizen            TEXT
);

CREATE INDEX ON archiv (pro_projnr);

COMMENT ON COLUMN archiv.id IS 'Eindeutiger Schlüssel in der Tabelle';
COMMENT ON COLUMN archiv.pro_projnr IS 'Die Ablage kann eine Projektablage sein';
COMMENT ON COLUMN archiv.speicherdatum IS 'Datum der Ablage im Speicher';
COMMENT ON COLUMN archiv.speicherakt IS 'Befindet sich auch der Akt zu einem Projekt im Speicher (0,1)';
COMMENT ON COLUMN archiv.speicherrechnungen IS 'Befinden sich auch die Rechnungen zu einem Projekt im Speicher (0,1)';
COMMENT ON COLUMN archiv.mikrodatplan IS 'Bestelldatum der Microfiche (neu: Feb 2013)';
COMMENT ON COLUMN archiv.mikrodat IS 'Datum an dem die Microfiche erhalten und eingelagert wurden (neu: Feb 2013)';
COMMENT ON COLUMN archiv.notizen IS 'Notizen als Freitext zu einer Ablage';
COMMENT ON TABLE archiv IS 'Beschreibt welche allgemeinen Dokumente und Projektakten und Mikrofiche im Archiv liegen. Diese Ablagen können projektbezogen sein, aber auch Dokumente allgemeiner Natur. Das Archiv selbst befindet sich im Speicher des Rathauses (dbase: speicher und mik)';
--------------------------------------------------------
--  benutzerhinweise
--------------------------------------------------------

CREATE TABLE benutzerhinweise
(
    view_id               VARCHAR(30) PRIMARY KEY,
    funktionsbeschreibung TEXT,
    bedienung             TEXT,
    pruefung_vorgaben     TEXT
);

COMMENT ON COLUMN benutzerhinweise.view_id IS 'ID der View, für den die Benutzerhinweise gelten';
COMMENT ON COLUMN benutzerhinweise.funktionsbeschreibung IS 'Text für die Funktionsbeschreibung';
COMMENT ON COLUMN benutzerhinweise.bedienung IS 'Text für die Bedienung';
COMMENT ON COLUMN benutzerhinweise.pruefung_vorgaben IS 'Text für Prüfungen und Vorgaben';
COMMENT ON TABLE benutzerhinweise IS 'Enthält Benutzerhinweise im Kontext einer View und dient damit als editierbare Benutzerhilfe';
--------------------------------------------------------
--  publikationen
--------------------------------------------------------

CREATE TABLE publikationen
(
    kurzform    VARCHAR(1) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN publikationen.kurzform IS 'Kurzform der EU nahen Publikation';
COMMENT ON COLUMN publikationen.bezeichnung IS 'Beschreibung der EU nahen Publikation';
COMMENT ON TABLE publikationen IS 'Enthält Kurzformen EU naher Publikationen';
--------------------------------------------------------
--  euinformationen
--------------------------------------------------------

CREATE TABLE euinformationen
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jahr         NUMERIC(4)            NOT NULL,
    pub_kurzform VARCHAR(1)            NOT NULL REFERENCES publikationen (kurzform),
    hefta        VARCHAR(1),
    nummer       NUMERIC(3)            NOT NULL,
    wichtig      BOOLEAN DEFAULT FALSE NOT NULL,
    seitennr     VARCHAR(3),
    stichwort    VARCHAR(50),
    rawi         BOOLEAN DEFAULT FALSE NOT NULL,
    schulref     BOOLEAN DEFAULT FALSE NOT NULL,
    sozref_r_5   BOOLEAN DEFAULT FALSE NOT NULL,
    rgu_11       BOOLEAN DEFAULT FALSE NOT NULL,
    rgu_cs       BOOLEAN DEFAULT FALSE NOT NULL,
    krh          BOOLEAN DEFAULT FALSE NOT NULL,
    afa          BOOLEAN DEFAULT FALSE NOT NULL,
    swm          BOOLEAN DEFAULT FALSE NOT NULL,
    kulturref    BOOLEAN DEFAULT FALSE NOT NULL,
    bauref       BOOLEAN DEFAULT FALSE NOT NULL,
    planref      BOOLEAN DEFAULT FALSE NOT NULL,
    direktorium  BOOLEAN DEFAULT FALSE NOT NULL,
    por          BOOLEAN DEFAULT FALSE NOT NULL,
    kvr          BOOLEAN DEFAULT FALSE NOT NULL,
    kommref      BOOLEAN DEFAULT FALSE NOT NULL,
    sew          BOOLEAN DEFAULT FALSE NOT NULL,
    stk          BOOLEAN DEFAULT FALSE NOT NULL,
    inhalt       VARCHAR(200)          NOT NULL,
    infodat      DATE
);

COMMENT ON COLUMN euinformationen.id IS 'Primary Key';
COMMENT ON COLUMN euinformationen.jahr IS 'Jahr der Erscheinung';
COMMENT ON COLUMN euinformationen.pub_kurzform IS 'Publikation';
COMMENT ON COLUMN euinformationen.hefta IS 'Zusatzbezeichnung zur Publikation';
COMMENT ON COLUMN euinformationen.nummer IS 'Nummer des Heftes';
COMMENT ON COLUMN euinformationen.wichtig IS 'Information weitergeben';
COMMENT ON COLUMN euinformationen.seitennr IS 'Seitennummer inerhalb des Heftes';
COMMENT ON COLUMN euinformationen.stichwort IS 'Stichwort zu dieser Infomation';
COMMENT ON COLUMN euinformationen.rawi IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.schulref IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.sozref_r_5 IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.rgu_11 IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.rgu_cs IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.krh IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.afa IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.swm IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.kulturref IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.bauref IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.planref IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.direktorium IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.por IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.kvr IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.kommref IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.sew IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.stk IS 'Soll dieses Referat informiert werden';
COMMENT ON COLUMN euinformationen.inhalt IS 'Kurzbeschreibung der Information';
COMMENT ON COLUMN euinformationen.infodat IS 'Datum der Information';
COMMENT ON TABLE euinformationen IS 'Enthält wesentliche Informationen diverses EU-naher Publikationen und ist Basis einer eigenständigen Applikation (dbase:eu)';
--------------------------------------------------------
--  geplantemassnahmen
--------------------------------------------------------

CREATE TABLE geplantemassnahmen
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kur_kurzbez     VARCHAR(8) NOT NULL REFERENCES kurzbezeichnungen (kurzbez),
    bez_stadtbezirk NUMERIC(2) REFERENCES stadtbezirke (stadtbezirk),
    strasse         VARCHAR(50),
    projekt         VARCHAR(70),
    baubeginn       NUMERIC(4),
    angelegt        NUMERIC(4),
    plannr          VARCHAR(10)
);

COMMENT ON COLUMN geplantemassnahmen.id IS 'Primary Key';
COMMENT ON COLUMN geplantemassnahmen.kur_kurzbez IS 'Kurzform der Projektkategorie für das Vorhaben';
COMMENT ON COLUMN geplantemassnahmen.bez_stadtbezirk IS 'Stadtbezirk der geplanten Maßnahme';
COMMENT ON COLUMN geplantemassnahmen.strasse IS 'Strasse des Vorhabens';
COMMENT ON COLUMN geplantemassnahmen.projekt IS 'Projektbezeichnung';
COMMENT ON COLUMN geplantemassnahmen.baubeginn IS 'Geplanter Baubeginn (Jahr)';
COMMENT ON COLUMN geplantemassnahmen.angelegt IS 'Vorgang angelegt (Jahr)';
COMMENT ON COLUMN geplantemassnahmen.plannr IS 'Nummer des Bebauungsplans';
COMMENT ON TABLE geplantemassnahmen IS 'Enthält Infomationen über zukünftige, geplanten Maßnahmen die mal in Projekte münden sollen (dbase:geplmasn)';
--------------------------------------------------------
--  hhjahre
--------------------------------------------------------

CREATE TABLE hhjahre
(
    hhjahr        NUMERIC(4) PRIMARY KEY,
    hhbezeichnung VARCHAR(200) NOT NULL,
    notizen       TEXT
);

COMMENT ON COLUMN hhjahre.hhjahr IS 'Haushaltsjahr';
COMMENT ON COLUMN hhjahre.hhbezeichnung IS 'Bezeichnung des Haushaltsjahres';
COMMENT ON COLUMN hhjahre.notizen IS 'Notizen und Protokoll zu einem Haushaltsjahr';
COMMENT ON TABLE hhjahre IS 'Aufstellung aller Haushaltsjahre';
--------------------------------------------------------
--  hhplan
--------------------------------------------------------

CREATE TABLE hhplan
(
    hhj_jahr          NUMERIC(4)                            NOT NULL REFERENCES hhjahre (hhjahr),
    pro_projnr        VARCHAR(7)                            NOT NULL REFERENCES projekte (projnr),
    p_pstrasse        VARCHAR(100),
    p_pname           VARCHAR(100),
    p_fob_fb          NUMERIC(2),
    p_bez_stadtbezirk NUMERIC(2),
    p_lna_kurzbez     VARCHAR(3),
    p_vndat           DATE,
    mitteleinplanung  NUMERIC(12),
    bewilligung_voj   NUMERIC(12),
    bewilligung_hhj   NUMERIC(12),
    erhalten_voj      NUMERIC(12),
    erhalten_hhj      NUMERIC(12),
    baustandaktuell   NUMERIC(12, 2),
    an                NUMERIC(12),
    n1                NUMERIC(12),
    n2                NUMERIC(12),
    notizen           TEXT,
    anlagedatum       DATE        DEFAULT CURRENT_DATE      NOT NULL,
    anlagevon         VARCHAR(30)                           NOT NULL,
    aenderungsdatum   DATE,
    aenderungvon      VARCHAR(30),
    fipo              VARCHAR(15) DEFAULT '000000000000000' NOT NULL,
    PRIMARY KEY (hhj_jahr, pro_projnr)
);

CREATE INDEX ON hhplan (pro_projnr);

COMMENT ON COLUMN hhplan.hhj_jahr IS 'Planung für ein Haushaltsjahr';
COMMENT ON COLUMN hhplan.fipo IS 'Planung für eine FIPO (Haushaltsstelle) des Projekts (Zuwendungen oder Konnexität)';
COMMENT ON COLUMN hhplan.pro_projnr IS 'Planung für ein Projekt innerhalb eines Haushaltsjahres';
COMMENT ON COLUMN hhplan.p_pstrasse IS 'Strasse aus Projekt übernommen';
COMMENT ON COLUMN hhplan.p_pname IS 'Projektname aus Projekt übernommen';
COMMENT ON COLUMN hhplan.p_fob_fb IS 'Förderbereich aus Projekt übernommen';
COMMENT ON COLUMN hhplan.p_bez_stadtbezirk IS 'Stadtbezirk aus Projekt übernommen';
COMMENT ON COLUMN hhplan.p_lna_kurzbez IS 'Bezirksliste übernommen';
COMMENT ON COLUMN hhplan.p_vndat IS 'VN Datum aus Projekt übernommen';
COMMENT ON COLUMN hhplan.mitteleinplanung IS 'Mitteleinplanung zum Zeitpunkt der Erstellung der Planung.';
COMMENT ON COLUMN hhplan.bewilligung_voj IS 'Bewilligte Zuwendungen in den Vorjahren.';
COMMENT ON COLUMN hhplan.bewilligung_hhj IS 'Bewilligte Zuwendungen im Haushaltsjahr.';
COMMENT ON COLUMN hhplan.erhalten_voj IS 'Erhaltene Zuwendungen in den Vorjahren.';
COMMENT ON COLUMN hhplan.erhalten_hhj IS 'Erhaltene Zuwendungen im Haushaltsjahr.';
COMMENT ON COLUMN hhplan.baustandaktuell IS 'Baustand zum Zeitpunkt der Erstellung der Planung.';
COMMENT ON COLUMN hhplan.an IS 'Ansatz im Nov des Vorjahres. Wird manuell erfasst.';
COMMENT ON COLUMN hhplan.n1 IS '1. Nachtrag im April des Haushaltsjahres. Wird manuell erfasst.';
COMMENT ON COLUMN hhplan.n2 IS '2. Nachtrag im August des Haushaltsjahres. Wird manuell erfasst.';
COMMENT ON COLUMN hhplan.notizen IS 'Notizen und Anmerkungen bezüglich einer Position im Haushaltsplan';
COMMENT ON COLUMN hhplan.anlagedatum IS 'Dieser Satz wurde angelegt am';
COMMENT ON COLUMN hhplan.anlagevon IS 'Dieser Satz wurde angelegt von diesem Benutzer';
COMMENT ON COLUMN hhplan.aenderungsdatum IS 'Dieser Satz wurde zuletzt geändert am';
COMMENT ON COLUMN hhplan.aenderungvon IS 'Dieser Satz wurde zuletzt geändert von diesem Benutzer';
COMMENT ON TABLE hhplan IS 'Enthält Einnahmen (Zuwendungen und Kostenerstattungen) je Projekt und Jahr und FIPO. Ist Basis für die jährliche Aufstellung der Haushaltsplanung (dbase:haush)';
--------------------------------------------------------
--  jahresstatistik
--------------------------------------------------------

CREATE TABLE jahresstatistik
(
    jahr                 NUMERIC(4) PRIMARY KEY,
    jahresstatistik1_am  DATE,
    jahresstatistik1_von VARCHAR(30),
    jahresstatistik2_am  DATE,
    jahresstatistik2_von VARCHAR(30),
    jahresstatistik3_am  DATE,
    jahresstatistik3_von VARCHAR(30),
    notizen              TEXT
);

COMMENT ON COLUMN jahresstatistik.jahr IS 'Jahr der Statistik';
COMMENT ON COLUMN jahresstatistik.jahresstatistik1_am IS 'Die Jahresstatistik I wurde zuletzt zu diesem Zeitpunkt erstellt';
COMMENT ON COLUMN jahresstatistik.jahresstatistik1_von IS 'Die Jahresstatistik I wurde zuletzt von diesem Benutzer erstellt';
COMMENT ON COLUMN jahresstatistik.jahresstatistik2_am IS 'Die Jahresstatistik II wurde zuletzt zu diesem Zeitpunkt erstellt';
COMMENT ON COLUMN jahresstatistik.jahresstatistik2_von IS 'Die Jahresstatistik II wurde zuletzt von diesem Benutzer erstellt';
COMMENT ON COLUMN jahresstatistik.jahresstatistik3_am IS 'Die Jahresstatistik III wurde zuletzt zu diesem Zeitpunkt erstellt';
COMMENT ON COLUMN jahresstatistik.jahresstatistik3_von IS 'Die Jahresstatistik III wurde zuletzt von diesem Benutzer erstellt';
COMMENT ON COLUMN jahresstatistik.notizen IS 'Allgemeine Notizen';
COMMENT ON TABLE jahresstatistik IS 'Diese Tabelle protokolliert die Erstellung der drei Jahresstatistiken';
--------------------------------------------------------
--  jahresstatistik1
--------------------------------------------------------

CREATE TABLE jahresstatistik1
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jss_jahr         NUMERIC(4)  NOT NULL REFERENCES jahresstatistik (jahr),
    foerderbereich   VARCHAR(60) NOT NULL,
    fb               NUMERIC(2)  NOT NULL,
    gruppe           NUMERIC(1)  NOT NULL,
    gesamtkosten     NUMERIC(12, 2),
    zuwendungsfaehig NUMERIC(12, 2),
    b_zuschuss       NUMERIC(12, 2),
    b_darlehen       NUMERIC(12, 2),
    b_konnexitaet    NUMERIC(12, 2),
    e_zuschuss       NUMERIC(12, 2),
    e_darlehen       NUMERIC(12, 2),
    e_konnexitaet    NUMERIC(12, 2)
);

COMMENT ON COLUMN jahresstatistik1.id IS 'ID als Sortierungskriterium';
COMMENT ON COLUMN jahresstatistik1.jss_jahr IS 'Jahr der Statistik';
COMMENT ON COLUMN jahresstatistik1.foerderbereich IS 'Beschreibung des Förderbereichs';
COMMENT ON COLUMN jahresstatistik1.fb IS 'Nummer des Förderbereichs';
COMMENT ON COLUMN jahresstatistik1.gruppe IS 'Gruppenkennzeichen (1) FAG ohne KIGA  (2) FAG KIGA  (3) alle anderen FB  für Zwischensummen';
COMMENT ON COLUMN jahresstatistik1.gesamtkosten IS 'Gesamtkosten im Erstantrag';
COMMENT ON COLUMN jahresstatistik1.zuwendungsfaehig IS 'Zuwendungsfähige Kosten im Erstantrag';
COMMENT ON COLUMN jahresstatistik1.b_zuschuss IS 'Bewilligter Zuschuss  im Jahr';
COMMENT ON COLUMN jahresstatistik1.b_darlehen IS 'Bewilligtes Darlehen  im Jahr';
COMMENT ON COLUMN jahresstatistik1.b_konnexitaet IS 'Bewilligte Konnexität im Jahr';
COMMENT ON COLUMN jahresstatistik1.e_zuschuss IS 'Erhaltener Zuschuss  im Jahr';
COMMENT ON COLUMN jahresstatistik1.e_darlehen IS 'Erhaltenes Darlehen  im Jahr';
COMMENT ON COLUMN jahresstatistik1.e_konnexitaet IS 'Erhaltene Konnexität im Jahr';
COMMENT ON TABLE jahresstatistik1 IS 'Diese Tabelle enthält die generierte Jahresstatistik für Seite I';
--------------------------------------------------------
--  jahresstatistik2
--------------------------------------------------------

CREATE TABLE jahresstatistik2
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jss_jahr             NUMERIC(4)  NOT NULL REFERENCES jahresstatistik (jahr),
    foerderbereich       VARCHAR(60) NOT NULL,
    fb                   NUMERIC(2)  NOT NULL,
    gruppe               NUMERIC(1)  NOT NULL,
    anzahl_abrufe        NUMERIC(10),
    anzahl_vn            NUMERIC(10),
    anzahl_bewilligungen NUMERIC(10),
    vngeskosten          NUMERIC(12, 2),
    anzahl_erst          NUMERIC(10),
    a_su_z_erst          NUMERIC(12, 2),
    a_su_k_erst          NUMERIC(12, 2),
    anzahl_folge         NUMERIC(10),
    a_su_z_folge         NUMERIC(12, 2),
    a_su_k_folge         NUMERIC(12, 2),
    a_vor_su_z_gesamt    NUMERIC(12, 2),
    a_vor_su_k_gesamt    NUMERIC(12, 2),
    anzahl_unbed         NUMERIC(10)
);

COMMENT ON COLUMN jahresstatistik2.id IS 'ID als Sortierkriterium';
COMMENT ON COLUMN jahresstatistik2.jss_jahr IS 'Jahr der Statistik';
COMMENT ON COLUMN jahresstatistik2.foerderbereich IS 'Beschreibung des Förderbereichs';
COMMENT ON COLUMN jahresstatistik2.fb IS 'Nummer des Förderbereichs';
COMMENT ON COLUMN jahresstatistik2.gruppe IS 'Gruppenkennzeichen für Zwischensummen';
COMMENT ON COLUMN jahresstatistik2.anzahl_abrufe IS 'Anzahl der Abrufe eines Jahres';
COMMENT ON COLUMN jahresstatistik2.anzahl_vn IS 'Anzahl der Verwendungsnachweise eines Jahres';
COMMENT ON COLUMN jahresstatistik2.anzahl_bewilligungen IS 'Anzahl der Bewilligungen eines Jahres';
COMMENT ON COLUMN jahresstatistik2.vngeskosten IS 'Endkosten im Verwendungsnachweis';
COMMENT ON COLUMN jahresstatistik2.anzahl_erst IS 'Anzahl der Erstanträge eines Jahres';
COMMENT ON COLUMN jahresstatistik2.a_su_z_erst IS 'Zuwendungen bei Erstanträgen in einem Jahr';
COMMENT ON COLUMN jahresstatistik2.a_su_k_erst IS 'Konnexität bei Erstanträgen in einem Jahr';
COMMENT ON COLUMN jahresstatistik2.anzahl_folge IS 'Anzahl der Folgeanträge eines Jahres';
COMMENT ON COLUMN jahresstatistik2.a_su_z_folge IS 'Zuwendungen bei Folgeanträgen in einem Jahr';
COMMENT ON COLUMN jahresstatistik2.a_su_k_folge IS 'Konnexität bei Folgeanträgen in einem Jahr';
COMMENT ON COLUMN jahresstatistik2.a_vor_su_z_gesamt IS 'Voraussichtliche Gesamtzuwendung über alle Anträge eines Jahres';
COMMENT ON COLUMN jahresstatistik2.a_vor_su_k_gesamt IS 'Voraussichtliche Gesamtkonnexität über alle Anträge eines Jahres';
COMMENT ON COLUMN jahresstatistik2.anzahl_unbed IS 'Anzahl der Unbedenklichkeitsanträge eines Jahres';
COMMENT ON TABLE jahresstatistik2 IS 'Diese Tabelle enthält die generierte Jahresstatistik für Seite II';
--------------------------------------------------------
--  jahresstatistik3
--------------------------------------------------------

CREATE TABLE jahresstatistik3
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jss_jahr           NUMERIC(4)  NOT NULL REFERENCES jahresstatistik (jahr),
    foerderbereich     VARCHAR(60) NOT NULL,
    fb                 NUMERIC(2)  NOT NULL,
    gruppe             NUMERIC(1)  NOT NULL,
    bzuwendung_z_plus  NUMERIC(12, 2),
    bzuwendung_z_minus NUMERIC(12, 2),
    bzuwendung_d_plus  NUMERIC(12, 2),
    bzuwendung_d_minus NUMERIC(12, 2),
    bzuwendung_k_plus  NUMERIC(12, 2),
    bzuwendung_k_minus NUMERIC(12, 2),
    erh_z              NUMERIC(12, 2),
    erh_d              NUMERIC(12, 2),
    erh_k              NUMERIC(12, 2)
);

COMMENT ON COLUMN jahresstatistik3.id IS 'ID als Sortierkriterium';
COMMENT ON COLUMN jahresstatistik3.jss_jahr IS 'Jahr der Statistik';
COMMENT ON COLUMN jahresstatistik3.foerderbereich IS 'Beschreibung des Förderbereichs';
COMMENT ON COLUMN jahresstatistik3.fb IS 'Nummer des Förderbereichs';
COMMENT ON COLUMN jahresstatistik3.gruppe IS 'Gruppenkennzeichen für Zwischensummen';
COMMENT ON COLUMN jahresstatistik3.bzuwendung_z_plus IS 'Bewilligter Zuschuss im Jahr (positiver Wert)';
COMMENT ON COLUMN jahresstatistik3.bzuwendung_z_minus IS 'Bewilligter Zuschuss im Jahr (negativer Wert)';
COMMENT ON COLUMN jahresstatistik3.bzuwendung_d_plus IS 'Bewilligtes Darlehen im Jahr (positiver Wert)';
COMMENT ON COLUMN jahresstatistik3.bzuwendung_d_minus IS 'Bewilligtes Darlehen im Jahr (negativer Wert)';
COMMENT ON COLUMN jahresstatistik3.bzuwendung_k_plus IS 'Bewilligte Konnexität im Jahr (positiver Wert)';
COMMENT ON COLUMN jahresstatistik3.bzuwendung_k_minus IS 'Bewilligte Konnexität im Jahr (negativer Wert)';
COMMENT ON COLUMN jahresstatistik3.erh_z IS 'Erhaltener Zuschuss im Jahr';
COMMENT ON COLUMN jahresstatistik3.erh_d IS 'Erhaltenes Darlehen im Jahr';
COMMENT ON COLUMN jahresstatistik3.erh_k IS 'Erhaltene Konnexität im Jahr';
COMMENT ON TABLE jahresstatistik3 IS 'Diese Tabelle enthält die generierte Jahresstatistik für Seite II';
--------------------------------------------------------
--  listennamen
--------------------------------------------------------

CREATE TABLE listennamen
(
    kurzbez     VARCHAR(3) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN listennamen.kurzbez IS 'Kurzbezeichnung für eine Liste von Stadtbezirken';
COMMENT ON COLUMN listennamen.bezeichnung IS 'Beschreibung zu einem Listennamen';
COMMENT ON TABLE listennamen IS 'Alle Listennamen für die Zusammenstellung mehrerer Stadtbezirke';
--------------------------------------------------------
--  projektistkosten
--------------------------------------------------------

CREATE TABLE projektistkosten
(
    pro_projnr VARCHAR(7)  NOT NULL REFERENCES projekte (projnr),
    jahr       NUMERIC(4)  NOT NULL,
    monat      NUMERIC(2)  NOT NULL,
    istkosten  NUMERIC(12) NOT NULL,
    PRIMARY KEY (pro_projnr, jahr, monat)
);

CREATE INDEX ON projektistkosten (pro_projnr);

COMMENT ON COLUMN projektistkosten.pro_projnr IS 'IstKosten bezogen auf ein Förderprojekt';
COMMENT ON COLUMN projektistkosten.jahr IS 'IstKosten bezogen auf ein Jahr';
COMMENT ON COLUMN projektistkosten.monat IS 'IstKosten bezogen auf einen Monat (im Jahr)';
COMMENT ON COLUMN projektistkosten.istkosten IS 'Istkosten in Euro aktueller Gesamtstand';
COMMENT ON TABLE projektistkosten IS 'Enthält die Istkosten der Projekte in Form des monatlich aktuellen Gesamtwerts (dbase:pist, palt*). Diese Tabelle zeigt somit die Entwickung der IST-Kosten im Zeitverlauf jeweils summiert an.';
--------------------------------------------------------
--  projekttermine
--------------------------------------------------------

CREATE TABLE projekttermine
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_projnr   VARCHAR(7)            NOT NULL REFERENCES projekte (projnr),
    termin       DATE                  NOT NULL,
    zustaendig   VARCHAR(60),
    telefon      VARCHAR(30),
    notizen      TEXT,
    ueberwachung BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE INDEX ON projekttermine (pro_projnr);

COMMENT ON COLUMN projekttermine.id IS 'Primary Key als ID';
COMMENT ON COLUMN projekttermine.pro_projnr IS 'Projektbezug eines Termins';
COMMENT ON COLUMN projekttermine.termin IS 'Termin';
COMMENT ON COLUMN projekttermine.zustaendig IS 'Zuständigkeit im Baureferet';
COMMENT ON COLUMN projekttermine.telefon IS 'Telefon des Bauleiters bzw. der Kontaktperson';
COMMENT ON COLUMN projekttermine.notizen IS 'Notizen (Freitext)';
COMMENT ON COLUMN projekttermine.ueberwachung IS 'Kennzeichen für Terminüberwachung';
COMMENT ON TABLE projekttermine IS 'Enthält eine Terminverwaltung bezüglich Projekten (dbase:vnuanf)';
--------------------------------------------------------
--  stadtbezirkslisten
--------------------------------------------------------

CREATE TABLE stadtbezirkslisten
(
    lna_kurzbez     VARCHAR(3) NOT NULL REFERENCES listennamen (kurzbez),
    bez_stadtbezirk NUMERIC(2) NOT NULL REFERENCES stadtbezirke (stadtbezirk),
    bezeichnung     VARCHAR(200),
    PRIMARY KEY (lna_kurzbez, bez_stadtbezirk)
);

COMMENT ON COLUMN stadtbezirkslisten.lna_kurzbez IS 'Kurzbezeichnung der Stadtbezirksliste';
COMMENT ON COLUMN stadtbezirkslisten.bez_stadtbezirk IS 'Nummer des Stadtbezirks';
COMMENT ON COLUMN stadtbezirkslisten.bezeichnung IS 'Notizen zu diesem Eintrag';
COMMENT ON TABLE stadtbezirkslisten IS 'Zuordnung von Stadtbezirken zu einer Stadtbezirksliste';
--------------------------------------------------------
--  traeger
--------------------------------------------------------

CREATE TABLE traeger
(
    kurzform    NUMERIC(1) PRIMARY KEY,
    bezeichnung VARCHAR(200) NOT NULL
);

COMMENT ON COLUMN traeger.kurzform IS 'Kurzform für den Träger des Städtebauförderprogramms';
COMMENT ON COLUMN traeger.bezeichnung IS 'Beschreibung des Trägers des Städebauförderprogramms';
COMMENT ON TABLE traeger IS 'Enthält Träger der Städtebauförderprogramme';
--------------------------------------------------------
--  staedtebaufoerderungen
--------------------------------------------------------

CREATE TABLE staedtebaufoerderungen
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bdat         DATE,
    bnr          NUMERIC(4),
    bjahr        NUMERIC(4),
    betrag       NUMERIC(10),
    soz          BOOLEAN DEFAULT FALSE NOT NULL,
    azbank       VARCHAR(40),
    antrnr       NUMERIC(3),
    antrjahr     NUMERIC(4),
    azstk        VARCHAR(6),
    ausbet       NUMERIC(10),
    erhdat       DATE,
    tra_kurzform NUMERIC(1) REFERENCES traeger (kurzform),
    hst          VARCHAR(15),
    hulnr        VARCHAR(5),
    huljahr      NUMERIC(4),
    notizen      TEXT,
    projektname  VARCHAR(60),
    restlos      DATE,
    zahlanz      DATE,
    schuldurk    BOOLEAN DEFAULT FALSE NOT NULL,
    alt_lfdnr    NUMERIC(10)
);

COMMENT ON COLUMN staedtebaufoerderungen.id IS 'Eindeutiger Schluessel für einen Datensatz';
COMMENT ON COLUMN staedtebaufoerderungen.bdat IS 'Datum der Bewilligung';
COMMENT ON COLUMN staedtebaufoerderungen.bnr IS 'Bescheidnummer';
COMMENT ON COLUMN staedtebaufoerderungen.bjahr IS 'Jahr der Bewilligung';
COMMENT ON COLUMN staedtebaufoerderungen.betrag IS 'Bewilligter Betrag';
COMMENT ON COLUMN staedtebaufoerderungen.soz IS 'Kennzeichen Soz Stadt';
COMMENT ON COLUMN staedtebaufoerderungen.azbank IS 'Aktenzeichen der Bank';
COMMENT ON COLUMN staedtebaufoerderungen.antrnr IS 'Antragsnummer';
COMMENT ON COLUMN staedtebaufoerderungen.antrjahr IS 'Antragsjahr';
COMMENT ON COLUMN staedtebaufoerderungen.azstk IS 'Aktenzeichen der Stadtkämmerei';
COMMENT ON COLUMN staedtebaufoerderungen.ausbet IS 'Ausbezahlter Betrag';
COMMENT ON COLUMN staedtebaufoerderungen.erhdat IS 'Datum des Geldeingangs';
COMMENT ON COLUMN staedtebaufoerderungen.tra_kurzform IS 'Träger des Städtebauförderprogramms';
COMMENT ON COLUMN staedtebaufoerderungen.hst IS 'Haushaltsstelle der Stadt als Freitext';
COMMENT ON COLUMN staedtebaufoerderungen.hulnr IS 'Hül Nummer der Stadt';
COMMENT ON COLUMN staedtebaufoerderungen.huljahr IS 'Hül Jahr';
COMMENT ON COLUMN staedtebaufoerderungen.notizen IS 'Notizen';
COMMENT ON COLUMN staedtebaufoerderungen.projektname IS 'Name des Projekts';
COMMENT ON COLUMN staedtebaufoerderungen.restlos IS 'Datum der Restlosanzeige an Dienststelle';
COMMENT ON COLUMN staedtebaufoerderungen.zahlanz IS 'Zahlungsanzeige erhalten am';
COMMENT ON COLUMN staedtebaufoerderungen.schuldurk IS 'Schuldurkunde ausgestellt';
COMMENT ON COLUMN staedtebaufoerderungen.alt_lfdnr IS 'Lfdnr zur Altdatenübernahme der Memos';
COMMENT ON TABLE staedtebaufoerderungen IS 'Aufstellung aller Programme zur Städtebauförderung als eingeständige Anwendung (dbase:stadt)';